Items = {
    0x1389: {
        type       : 0x0000,
        name       : '恢复药',
        useInBattle: True,
        useInWorld : True,
        target     : 'Enemy',
        buyPrice   : 50,
        sellPrice  : 25,
        restoreHP  : 50,
    },

    0x138A: {
        type       : 0x0000,
        name       : '高级恢复药',
        useInBattle: True,
        useInWorld : True,
        target     : 'Enemy',
        buyPrice   : 600,
        sellPrice  : 300,
        restoreHP  : 500,
    },

    0x138B: {
        type       : 0x0000,
        name       : '解毒药',
        useInBattle: True,
        useInWorld : True,
        target     : 'Ailment',
        buyPrice   : 80,
        sellPrice  : 40,
        restoreHP  : 0,
    },

    0x138C: {
        type       : 0x0000,
        name       : '眼药',
        useInBattle: True,
        useInWorld : True,
        target     : 'Ailment',
        buyPrice   : 40,
        sellPrice  : 20,
        restoreHP  : 0,
    },

    0x138D: {
        type       : 0x0000,
        name       : '山彦草',
        useInBattle: True,
        useInWorld : True,
        target     : 'Ailment',
        buyPrice   : 100,
        sellPrice  : 50,
        restoreHP  : 0,
    },

    0x138E: {
        type       : 0x0000,
        name       : '金针',
        useInBattle: True,
        useInWorld : True,
        target     : 'Ailment',
        buyPrice   : 100,
        sellPrice  : 50,
        restoreHP  : 0,
    },

    0x138F: {
        type       : 0x0000,
        name       : '少女之吻',
        useInBattle: True,
        useInWorld : True,
        target     : 'Ailment',
        buyPrice   : 100,
        sellPrice  : 50,
        restoreHP  : 0,
    },

    0x1390: {
        type       : 0x0000,
        name       : '万宝槌',
        useInBattle: True,
        useInWorld : True,
        target     : 'Ailment',
        buyPrice   : 100,
        sellPrice  : 50,
        restoreHP  : 0,
    },

    0x1391: {
        type       : 0x0000,
        name       : '海獭头蘑菇',
        useInBattle: False,
        useInWorld : True,
        target     : 'Enemy',
        buyPrice   : 2000,
        sellPrice  : 1000,
        restoreHP  : 0,
    },

    0x1392: {
        type       : 0x0000,
        name       : '不死鸟之尾',
        useInBattle: True,
        useInWorld : True,
        target     : 'Ailment',
        buyPrice   : 999999,
        sellPrice  : 1,
        restoreHP  : 0,
    },

    0x1393: {
        type       : 0x0000,
        name       : '圣灵药',
        useInBattle: True,
        useInWorld : True,
        target     : 'Enemy',
        buyPrice   : 2,
        sellPrice  : 1,
        restoreHP  : 9999,
    },

    0x1394: {
        type       : 0x0000,
        name       : '小人面包',
        useInBattle: False,
        useInWorld : True,
        target     : 'Enemy',
        buyPrice   : 200,
        sellPrice  : 100,
        restoreHP  : 0,
    },

    0x1395: {
        type       : 0x0000,
        name       : '魔法钥匙',
        useInBattle: False,
        useInWorld : False,
        target     : 'Enemy',
        buyPrice   : 100,
        sellPrice  : 50,
        restoreHP  : 0,
    },

    0x1396: {
        type       : 0x0000,
        name       : '基萨尔野菜',
        useInBattle: False,
        useInWorld : False,
        target     : 'Enemy',
        buyPrice   : 150,
        sellPrice  : 75,
        restoreHP  : 0,
    },

    0x13ED: {
        type       : 0x0001,
        name       : '南极之风',
        useInBattle: True,
        useInWorld : False,
        target     : 'Ally',
        buyPrice   : 1000,
        sellPrice  : 500,
        restoreHP  : 1000,
    },

    0x13EE: {
        type       : 0x0001,
        name       : '宙斯之怒',
        useInBattle: True,
        useInWorld : False,
        target     : 'Ally',
        buyPrice   : 1000,
        sellPrice  : 500,
        restoreHP  : 1000,
    },

    0x13EF: {
        type       : 0x0001,
        name       : '爆弹碎片',
        useInBattle: True,
        useInWorld : False,
        target     : 'Ally',
        buyPrice   : 1000,
        sellPrice  : 500,
        restoreHP  : 1000,
    },

    0x13F0: {
        type       : 0x0001,
        name       : '拉米亚之鳞',
        useInBattle: True,
        useInWorld : False,
        target     : 'Ally',
        buyPrice   : 3000,
        sellPrice  : 1500,
        restoreHP  : 1000,
    },

    0x13F1: {
        type       : 0x0001,
        name       : '酒神之酒',
        useInBattle: True,
        useInWorld : False,
        target     : 'Enemy',
        buyPrice   : 3000,
        sellPrice  : 1500,
        restoreHP  : 1000,
    },

    0x13F2: {
        type       : 0x0001,
        name       : '麻醉针',
        useInBattle: True,
        useInWorld : False,
        target     : 'Ally',
        buyPrice   : 3000,
        sellPrice  : 1500,
        restoreHP  : 1000,
    },

    0x13F3: {
        type       : 0x0001,
        name       : '爆弹右臂',
        useInBattle: True,
        useInWorld : False,
        target     : 'Ally',
        buyPrice   : 1500,
        sellPrice  : 750,
        restoreHP  : 1000,
    },

    0x13F4: {
        type       : 0x0001,
        name       : '北极之风',
        useInBattle: True,
        useInWorld : False,
        target     : 'Ally',
        buyPrice   : 1500,
        sellPrice  : 750,
        restoreHP  : 1000,
    },

    0x13F5: {
        type       : 0x0001,
        name       : '众神之怒',
        useInBattle: True,
        useInWorld : False,
        target     : 'Ally',
        buyPrice   : 1500,
        sellPrice  : 750,
        restoreHP  : 1000,
    },

    0x13F6: {
        type       : 0x0001,
        name       : '大地之鼓',
        useInBattle: True,
        useInWorld : False,
        target     : 'Ally',
        buyPrice   : 2500,
        sellPrice  : 1250,
        restoreHP  : 1000,
    },

    0x13F7: {
        type       : 0x0001,
        name       : '龟甲壳',
        useInBattle: True,
        useInWorld : False,
        target     : 'Enemy',
        buyPrice   : 3000,
        sellPrice  : 1500,
        restoreHP  : 1000,
    },

    0x13F8: {
        type       : 0x0001,
        name       : '天使的叹息',
        useInBattle: True,
        useInWorld : False,
        target     : 'Ailment',
        buyPrice   : 3000,
        sellPrice  : 1500,
        restoreHP  : 0,
    },

    0x13F9: {
        type       : 0x0001,
        name       : '黑洞',
        useInBattle: True,
        useInWorld : False,
        target     : 'Ally',
        buyPrice   : 4000,
        sellPrice  : 2000,
        restoreHP  : 1000,
    },

    0x13FA: {
        type       : 0x0001,
        name       : '黑之香',
        useInBattle: True,
        useInWorld : False,
        target     : 'Ally',
        buyPrice   : 5000,
        sellPrice  : 2500,
        restoreHP  : 1000,
    },

    0x13FB: {
        type       : 0x0001,
        name       : '莉莉丝之吻',
        useInBattle: True,
        useInWorld : False,
        target     : 'Ally',
        buyPrice   : 3000,
        sellPrice  : 1500,
        restoreHP  : 1000,
    },

    0x13FC: {
        type       : 0x0001,
        name       : '天狗的哈欠',
        useInBattle: True,
        useInWorld : False,
        target     : 'Ally',
        buyPrice   : 3000,
        sellPrice  : 1500,
        restoreHP  : 1000,
    },

    0x13FD: {
        type       : 0x0001,
        name       : '龟甲破',
        useInBattle: True,
        useInWorld : False,
        target     : 'Ally',
        buyPrice   : 3000,
        sellPrice  : 1500,
        restoreHP  : 1000,
    },

    0x13FE: {
        type       : 0x0001,
        name       : '沉默之符',
        useInBattle: True,
        useInWorld : False,
        target     : 'Ally',
        buyPrice   : 2000,
        sellPrice  : 1000,
        restoreHP  : 1000,
    },

    0x13FF: {
        type       : 0x0001,
        name       : '绵羊枕',
        useInBattle: True,
        useInWorld : False,
        target     : 'Ally',
        buyPrice   : 2000,
        sellPrice  : 1000,
        restoreHP  : 1000,
    },

    0x1400: {
        type       : 0x0001,
        name       : '光之幕帘',
        useInBattle: True,
        useInWorld : False,
        target     : 'Enemy',
        buyPrice   : 5000,
        sellPrice  : 2500,
        restoreHP  : 1000,
    },

    0x1401: {
        type       : 0x0001,
        name       : '陆行鸟之怒',
        useInBattle: True,
        useInWorld : False,
        target     : 'Ally',
        buyPrice   : 5000,
        sellPrice  : 2500,
        restoreHP  : 1000,
    },

    0x1402: {
        type       : 0x0001,
        name       : '白之香',
        useInBattle: True,
        useInWorld : False,
        target     : 'Ally',
        buyPrice   : 5000,
        sellPrice  : 2500,
        restoreHP  : 1000,
    },

}
