items = {
    0xF424C: (0xCCCC0101, '  Fully restored.'),
    0x9D9FF5: (0xCCCC0101, 'Hein was King Argus's most trusted advisor.\nBut he was corrupted by darkness after the\nearthquake hit us.'),
    0x9DA059: (0xCCCC0101, 'This castle is the Elder Tree of the Living\nWoods. Hein put a curse on it, and carved tunnels\nand rooms inside its trunk.'),
    0x9DA0BD: (0xCCCC0101, 'Hein was corrupted by darkness, and obtained great\npower from it... And still, he hungers for more.'),
    0x9DA121: (0xCCCC0101, 'Use this to shrink yourselves--it is of no use to\nme now. There is a small hole in the rightmost\ncorner... Good luck.'),
    0x9DA121: (0xCCCC0101, 'Use this to shrink yourselves--it is of no use to\nme now. There is a small hole in the rightmost\ncorner... Good luck.'),
    0x9DA121: (0xCCCC0101, 'Use this to shrink yourselves--it is of no use to\nme now. There is a small hole in the rightmost\ncorner... Good luck.'),
    0x9DA121: (0xCCCC0101, 'Use this to shrink yourselves--it is of no use to\nme now. There is a small hole in the rightmost\ncorner... Good luck.'),
    0x9DA122: (0xCCCC0101, '  Obtained the spell Mini.'),
    0x9DA122: (0xCCCC0101, '  Obtained the spell Mini.'),
    0x9DA122: (0xCCCC0101, '  Obtained the spell Mini.'),
    0x9DA123: (0xCCCC0101, 'Go... You must defeat Hein.'),
    0x9DA185: (0xCCCC0101, 'Hein has hidden the royal sword of King\nArgus somewhere...'),
    0x9DA1E9: (0xCCCC0101, 'You are going to defeat Hein, you say?\nThat's interesting. Hmm. Yes. Well then.\nNow you must die!'),
    0x9DA24D: (0xCCCC0101, '  King Argus\nAs I said, you must defeat Hein!'),
    0x1363675: (0xCCCC0101, '  %shuyaku1%\nUngh...\nWhere...are we?'),
    0x1363676: (0xCCCC0101, '  %shuyaku4%\nWe have been imprisoned.\nLet us investigate the vicinity...'),
    0x13636D9: (0xCCCC0101, 'I am King Argus. I rule over the lands north of\nthe desert.'),
    0x13636D9: (0xCCCC0101, 'I am King Argus. I rule over the lands north of\nthe desert.'),
    0x13636DA: (0xCCCC0101, 'That is to say, the king of an empty kingdom, now\nthat Hein has cursed my soldiers into doing his\nbidding...'),
    0x13636DA: (0xCCCC0101, 'That is to say, the king of an empty kingdom, now\nthat Hein has cursed my soldiers into doing his\nbidding...'),
    0x13636DB: (0xCCCC0101, 'I had put my trust in him... His betrayal cannot be\nforgiven.\n*Cough* *Cough*'),
    0x13636DB: (0xCCCC0101, 'I had put my trust in him... His betrayal cannot be\nforgiven.\n*Cough* *Cough*'),
    0x13636DC: (0xCCCC0101, '  %shuyaku3%\nMilord...are you all right?'),
    0x13636DC: (0xCCCC0101, '  %shuyaku3%\nMilord...are you all right?'),
    0x13636DD: (0xCCCC0101, '  King Argus\nI am fine, thank you... But I must ask you to do\nsomething for me. You must defeat Hein!'),
    0x13636DD: (0xCCCC0101, '  King Argus\nI am fine, thank you... But I must ask you to do\nsomething for me. You must defeat Hein!'),
    0x136373D: (0xCCCC0101, '  %shuyaku1%\nIf only we could pass through this hole...'),
    0x136373D: (0xCCCC0101, '  %shuyaku1%\nIf only we could pass through this hole...'),
    0x136373E: (0xCCCC0101, '  %shuyaku2%\nIt's too small! We wouldn't be able to get through\nunless we shrunk ourselves...'),
    0x136373E: (0xCCCC0101, '  %shuyaku2%\nIt's too small! We wouldn't be able to get through\nunless we shrunk ourselves...'),
}