items = {
    0xF4496: (0xCCCC0101, 'Earth Crystal'),
    0xA36C55: (0xCCCC0101, '  You were able to restore the flow of time in this\n  world once, but if the darkness returns, your\n  efforts will have been for naught.'),
    0xA36C56: (0xCCCC0101, '  Warriors of the Light, you must seek Xande in\n  the Syrcus Tower, and stop his nefarious plan!'),
    0x13C02D5: (0xCCCC0101, '  %shuyaku1%\nIt's the earth crystal...'),
    0x13C02D7: (0xCCCC0101, 'By Master Xande's orders, you will be\ncrushed!!!'),
    0x13C0339: (0xCCCC0101, '  Warriors of the Light...'),
    0x13C0339: (0xCCCC0101, '  Warriors of the Light...'),
    0x13C033A: (0xCCCC0101, '  Xande is using my power for his own evil\n  purposes... He is trying to engulf this world\n  in darkness once again.'),
    0x13C033A: (0xCCCC0101, '  Xande is using my power for his own evil\n  purposes... He is trying to engulf this world\n  in darkness once again.'),
    0x13C033B: (0xCCCC0101, '  I will bless you with my power...\n  Use it to banish the darkness that threatens\n  this land!'),
    0x13C033B: (0xCCCC0101, '  I will bless you with my power...\n  Use it to banish the darkness that threatens\n  this land!'),
    0x13C033D: (0xCCCC0101, '  The Syrcus Tower, known to you mortals as\n  the "Crystal Tower," was created long ago\n  out of solid light.'),
    0x13C033D: (0xCCCC0101, '  The Syrcus Tower, known to you mortals as\n  the "Crystal Tower," was created long ago\n  out of solid light.'),
    0x13C033E: (0xCCCC0101, '  Xande has used this element against us,\n  and uses our power to bring forth the darkness.'),
    0x13C033E: (0xCCCC0101, '  Xande has used this element against us,\n  and uses our power to bring forth the darkness.'),
    0x13C0340: (0xCCCC0101, '  Warriors of the Light, seek out Xande in the\n  Syrcus Tower, and stop his nefarious plan!'),
    0x13C0340: (0xCCCC0101, '  Warriors of the Light, seek out Xande in the\n  Syrcus Tower, and stop his nefarious plan!'),
    0x13C0341: (0xCCCC0101, '  You have been blessed with the power of earth!'),
    0x13C0341: (0xCCCC0101, '  You have been blessed with the power of earth!'),
}