items = {
    0xA3E185: (0xCCCC0101, 'Resistance is futile.\nYou cannot hope to defeat us...'),
    0x13C7B25: (0xCCCC0101, 'We are the Cloud of Darkness...'),
    0x13C7B26: (0xCCCC0101, 'None shall stand before the flood of darkness.\nWith it, we will bring the Void to this world, and\nyour world of light as well...'),
    0x13C7B27: (0xCCCC0101, '  %shuyaku1%\nWe won't let you! Not if we have anything\nto say about it!'),
    0x13C7B28: (0xCCCC0101, 'Hah hah hah...\nThis is the world of darkness...you cannot defeat\nme with only the power of light!'),
    0x13C7B29: (0xCCCC0101, '  Warrior of the Dark\nThat is why we are here!'),
    0x13C7B2A: (0xCCCC0101, '  Warrior of the Dark\nThe hopes of light and darkness now unite!\nWe shall not let the Void reign free!'),
    0x13C7B2B: (0xCCCC0101, 'You are trying my patience!'),
    0x13C7B2C: (0xCCCC0101, 'You may have destroyed the dark crystals...\nbut that is of no consequence...'),
    0x13C7B2D: (0xCCCC0101, 'We will devour your power of light, and use\nit to return this world to the Void!'),
    0x13C9F15: (0xCCCC0101, '  In the beginning, there was the Void...\n  Then there was light, and darkness.\n  And then, everything was born.'),
    0x13C9F16: (0xCCCC0101, '  The sky, the land, water, fire...and life.\n  Time flows to bring them all back from\n  whence they came.'),
    0x13C9F17: (0xCCCC0101, '  But life gave birth to something unique.\n  A shining force that divided the light\n  and darkness, and illuminated the world...'),
    0x13C9F18: (0xCCCC0101, '  A force called Hope.'),
    0x13C9F19: (0xCCCC0101, '  A time will come again when the balance\n  between light and darkness is broken...\n  And four will be chosen to restore it.'),
    0x13C9F1A: (0xCCCC0101, '  Do not forget that what gives the four\n  their power...is Hope. Hope inside each\n  and every living being in the world.'),
    0x13C9F1B: (0xCCCC0101, '  Dreams, despair, love... Time will consume\n  all.'),
    0x13C9F1C: (0xCCCC0101, '  But you must not accept it. You must\n  fight it. You must find the power\n  within to prevail...'),
    0x13C9F1D: (0xCCCC0101, '  You must find the one last speck of\n  light... The one feeble glitter that will\n  illuminate all... The light of Hope...'),
}