items = {
    0x9F4DA6: (0xCCCC0101, '  You used the Chain Key.'),
    0x137E425: (0xCCCC0101, '  The party has met an untimely end...'),
    0x1D13DF5: (0xCCCC0101, '  Prince Alus\nMy father has changed... It is as if some evil\nspirit has taken ahold of him.'),
    0x1D13DF6: (0xCCCC0101, '  %shuyaku2%\nThere must be a reason for all this... I'm sure\nhe'll explain it to you when we meet him.'),
    0x1D13DF7: (0xCCCC0101, '  Prince Alus\nI would like to talk to him... But he told me to\nnever return to the castle.'),
    0x1D22855: (0xCCCC0101, '  Doga\nThe Circle leads to a rift between dimensions...\nAnd that is where the key to Eureka lies.'),
    0x1D22856: (0xCCCC0101, '  %shuyaku2%\nEureka...?'),
    0x1D22857: (0xCCCC0101, '  Doga\nEureka is the land where weapons of incredible\npower, created by the Ancients, are sealed.'),
    0x1D22858: (0xCCCC0101, 'Only these forbidden weapons, combined with\nthe power of the Warriors of the Light, will be\npowerful enough to defeat Xande.'),
    0x1D31319: (0xCCCC0101, '  Unei\nEven when Xande stopped the flow of time in the\nreal world, the world of dream was unaffected.'),
    0x1D3131A: (0xCCCC0101, 'For the thousand years that the real world\nstood still, I was watching it from the dreamworld...'),
    0x1D3131B: (0xCCCC0101, 'And I saw that something evil was using\nits power to create a giant earthquake on the\nfloating continent!'),
    0x1D3131C: (0xCCCC0101, '  Unei\nXande himself couldn't have done it, since the flow\nof time is stopped for him as well. Who could it be?'),
}