items = {
    0xF430A: (0xCCCC0101, '  Elder Topapa\nAh, %shuyaku1%. I have been waiting for you.'),
    0xF430B: (0xCCCC0101, 'The power of the crystal has grown weaker\nsince the earthquake hit us.'),
    0xF430C: (0xCCCC0101, 'I want you to investigate the cave up\nnorth, and the crystal that lies within.'),
    0xF430D: (0xCCCC0101, '  Elder Topapa\nThe crystal is in the cave to the north.'),
    0xF430E: (0xCCCC0101, '  Nina\nBe careful, %shuyaku1%.'),
    0xF430F: (0xCCCC0101, '  Elder Homak\nThere is a wellspring somewhere inside\nthe cave. You should investigate it as\nwell.'),
    0xF4310: (0xCCCC0101, 'Welcome to E3, kupo!'),
    0xF4311: (0xCCCC0101, 'Pleased to make your acquaintance!'),
    0xF4312: (0xCCCC0101, 'You can play this game by using either the\ntouch panel or the buttons, kupo!'),
    0xF4313: (0xCCCC0101, 'Aaand...you can control your viewpoint\nwith the L and R Buttons!'),
    0xF4314: (0xCCCC0101, 'See what I mean, kupo?'),
    0xF4315: (0xCCCC0101, 'Now, enjoy your sneak peek into the world\nof the brand-new FINAL FANTASY III, kupo!'),
    0xF4319: (0xCCCC0101, 'This game is currently under development\n            and may stop unexpectedly.\nCertain aspects may not be representative\n                  of the final product.'),
    0xF4561: (0xCCCC0101, '  Elder Topapa\n%shuyaku1%, thank you for coming. It seems the children\nhave gone to the Altar Cave...'),
    0xF4562: (0xCCCC0101, 'Could you go look for them?'),
    0xF4565: (0xCCCC0101, '  Elder Topapa\nThe children must be in the Altar Cave.\nCould you go look for them?'),
    0xF4575: (0xCCCC0101, '  Elder Topapa\nThe children are back safe and sound!\nYou have done a magnificent job!'),
    0xF4576: (0xCCCC0101, 'I will let you know if we need your help\nwith anything else.'),
    0x98E9B5: (0xCCCC0101, '  Elder Homak\n%shuyaku1%... You must treat Nina,\nyour mother, the very best you can.'),
    0x98E9B6: (0xCCCC0101, 'You must know by now that she is not\nyour birth mother, but she has taken\ncare of you as if she truly were.'),
    0x98ECD5: (0xCCCC0101, '  Nina\nSo this day has finally come...'),
    0x98ECD7: (0xCCCC0101, 'I'm going to worry about you,\nso promise me you'll be careful!'),
    0x98ECD8: (0xCCCC0101, '  Nina\nI'm going to worry about you,\nso promise me you'll be careful!'),
    0x98ECD9: (0xCCCC0101, 'If you run into trouble, try looking at\nthe "Control Hints".'),
    0x98ECD9: (0xCCCC0101, 'If you run into trouble, try looking at\nthe "Control Hints".'),
    0x98ECDA: (0xCCCC0101, 'You can find it by opening "Config 2"\nunder "Config".\nI'm sure it will aid you on your journey.'),
    0x98ECDA: (0xCCCC0101, 'You can find it by opening "Config 2"\nunder "Config".\nI'm sure it will aid you on your journey.'),
    0x98ECDB: (0xCCCC0101, 'And don't forget to save your progress\nfrequently, too!'),
    0x98ECDB: (0xCCCC0101, 'And don't forget to save your progress\nfrequently, too!'),
    0x98ED39: (0xCCCC0101, '  Elder Topapa\nYou must make your way to Kazus.\nGo swiftly, but go prepared!'),
    0x98ED3A: (0xCCCC0101, '  Elder Topapa\nYou have my praise for your deeds in Kazus.\nI wish you success on the rest of your journey.'),
    0x1317BE9: (0xCCCC0101, '  Elder Topapa\nYou have come, %shuyaku1%.\nSo it is you who has been chosen...'),
    0x1317BEA: (0xCCCC0101, 'You must understand that your meeting\nwith the crystal was not happenstance.'),
    0x1317BEB: (0xCCCC0101, 'It was the crystal's will.\nYou have been chosen.'),
    0x1317BEC: (0xCCCC0101, '  %shuyaku1%\nChosen? For what?\nI don't understand.'),
    0x1317BED: (0xCCCC0101, '  Elder Topapa\nA long time ago, a traveler came to me\ncarrying a newborn child.'),
    0x1317BEE: (0xCCCC0101, 'His face was covered in soot and his clothes\nwere burnt to tatters.\nThe child he carried in his arms...was you.'),
    0x1317BEF: (0xCCCC0101, 'To think, even as a newborn, you were already\ndestined to be chosen by the crystal...'),
    0x1317BF1: (0xCCCC0101, 'You must now set forth on your journey.\nTake your power, the light you hold\nin your heart, and use it well!'),
}