items = {
    0xF45F6: (0xCCCC0101, '  Takka\nBack so soon? Is your journey done, or is\nthere something I can do for you?'),
    0xF45F7: (0xCCCC0101, '  %shuyaku3%\nThe princess of Castle Sasune gave us this\npendant... It's broken. Can you fix it, Father?'),
    0xF45F8: (0xCCCC0101, '  Takka\nLemme see now...'),
    0xF45F9: (0xCCCC0101, '  Takka\nHmm... I have no idea what this is made\nof. I've never seen anything like it.'),
    0xF45FA: (0xCCCC0101, 'Making mythril rams is one thing, but this...\nNo, I'm sorry. I can't help you.'),
    0xF45FB: (0xCCCC0101, '  %shuyaku3%\nOkay... I guess we'll have to find someone\nelse.'),
    0x990E6D: (0xCCCC0101, '  Takka\nWhat? How many times do I have to say it?\nNo, I don't have any mythril rings!'),
    0x990E6E: (0xCCCC0101, 'I want to get rid of this curse as much as you,\nbut how am I to temper mythril as a ghost?'),
    0x990E6F: (0xCCCC0101, 'Even if I weren't cursed, I couldn't work unless\nI knew my daughter was safe. It's all my fault...\nI shouldn't have been so harsh in training her.'),
    0x99F8CD: (0xCCCC0101, '  Takka\n...Eh? Whazzat? What do you want?\nCan't you see I'm busy?'),
    0x99F8CE: (0xCCCC0101, '  Takka\nBusy busy busy busy busy busy busy...'),
    0x99F8CF: (0xCCCC0101, '  Takka\nHey, %shuyaku3%!\nAre you doing okay? They feeding you?'),
    0x99F8D0: (0xCCCC0101, 'Come back home safe, you hear?'),
    0x99F931: (0xCCCC0101, '  %shuyaku3%\nI'm sorry...'),
    0x99F932: (0xCCCC0101, 'I want to go with you, but I don't\nthink Father would let me...'),
    0x1328DBD: (0xCCCC0101, '  Takka\nCid, you old dog! It's good to see you--\nand not through you--again!'),
    0x1328DBE: (0xCCCC0101, '  Cid\nYeah, I hear ya. Say, Takka, we were thinking\nof busting that rock in Nelv with the airship...'),
    0x1328DBF: (0xCCCC0101, 'But I reckon we'd need a mythril ram on the\nship's bow. Think you can hack one together?'),
    0x1328DC0: (0xCCCC0101, '  Takka\nA mythril ram, eh...? Sounds feasible...\nWait here, and I'll smith you one in no time!'),
    0x1328DC1: (0xCCCC0101, '%shuyaku3%! Gimme a hand or three, will you?'),
    0x1328DC2: (0xCCCC0101, '  Takka\nDone and done! Your airship has been fitted\nwith the ram. You'll find it outside Kazus.'),
    0x1328DC3: (0xCCCC0101, '  Cid\nSterling handiwork as always, Takka.\nAnd fast, too.'),
    0x1328DCD: (0xCCCC0101, 'Let's set 'er up and bust some\nboulders!'),
}