items = {
    0x990C79: (0xCCCC0101, 'The Djinn that we had banished into the Sealed\nCave was released by the earthquake...and\ncast a curse on us all!'),
    0x990CDD: (0xCCCC0101, 'If only we had the mythril ring that the\nblacksmith had forged... It is the only\nthing that may banish the Djinn!'),
    0x990D41: (0xCCCC0101, 'Have you been to this town's mythril mines?\nI'm gonna tell you a secret, so listen up:\nthere's a hidden passageway in those tunnels!'),
    0x990D41: (0xCCCC0101, 'Have you been to this town's mythril mines?\nI'm gonna tell you a secret, so listen up:\nthere's a hidden passageway in those tunnels!'),
    0x990D42: (0xCCCC0101, 'I heard you can find it in the corner of\nthe first room. I'd go look for it...but that\nplace gives me the heebie-jeebies.'),
    0x990D42: (0xCCCC0101, 'I heard you can find it in the corner of\nthe first room. I'd go look for it...but that\nplace gives me the heebie-jeebies.'),
    0x990DA5: (0xCCCC0101, 'Only the power of mythril can banish\nthe Djinn.'),
    0x990DA6: (0xCCCC0101, 'That is why the Djinn cursed this town\nonce it found out how the nearby mines\nwere packed with the stuff.'),
    0x990ED1: (0xCCCC0101, '  Cid\nMy airship's hidden in the desert west of here.\nI'm counting on you!'),
    0x99F675: (0xCCCC0101, 'Look! I'm not a ghost anymore!\nAhh, sweet mortality, how I've missed you!'),
    0x131A2F9: (0xCCCC0101, 'Howdy there! Cid's the name. I'm from Canaan,\nbut I've been stuck here ever since Nelv\nValley got blocked by a giant rock.'),
    0x131A2F9: (0xCCCC0101, 'Howdy there! Cid's the name. I'm from Canaan,\nbut I've been stuck here ever since Nelv\nValley got blocked by a giant rock.'),
    0x131A2FA: (0xCCCC0101, 'On top of that, I got a curse cast on me\nalong with these other folks. Ain't that a\ntrip an' a half? Hah hah hah!'),
    0x131A2FA: (0xCCCC0101, 'On top of that, I got a curse cast on me\nalong with these other folks. Ain't that a\ntrip an' a half? Hah hah hah!'),
    0x131A2FB: (0xCCCC0101, '  %shuyaku2%\n%shuyaku1%! We have to do something to help\nthese people!'),
    0x131A2FD: (0xCCCC0101, '  Cid\nSay, if I lent you my airship, do you lads\nthink you could help me and these other saps?'),
    0x131A2FE: (0xCCCC0101, 'From what I hear, this curse can be dispelled\nthrough the power of a mythril ring. Unfortunately,\nwe all seem to be out of mythril rings here...'),
    0x131A2FF: (0xCCCC0101, 'Even if we could get the mythril, Takka the smith\nhas been turned into a ghost himself...and his\ndaughter, the apprentice, has gone missing!'),
    0x131A300: (0xCCCC0101, 'My airship's hidden in the desert west of here.\nUse it to find a way to lift this curse!'),
    0x131A309: (0xCCCC0101, 'Keep in mind you can get on or off the airship\nby pressing %s.'),
    0x131A30A: (0xCCCC0101, 'The same goes for all other vehicles, too, you got that?'),
    0x1328D59: (0xCCCC0101, '  Cid\nGood work! I knew you'd pull it\noff the moment I saw you!'),
    0x1328D5A: (0xCCCC0101, 'I'm guessing you can make better\nuse of my airship than I can myself!'),
    0x1328D5B: (0xCCCC0101, 'But first, I want you to take me back\nto Canaan. Mrs. Cid's been waiting a\nmighty long time for me to come back!'),
    0x1328D5C: (0xCCCC0101, '  Cid has joined the party!'),
}