items = {
    0xF42AE: (0xCCCC0101, '  %shuyaku1%\nThere's nobody here...'),
    0xF42B0: (0xCCCC0101, '  %shuyaku2%\nThere's no one here.\nLet's go back.'),
    0xF42B1: (0xCCCC0101, '  %shuyaku1%\nYeah...'),
    0xF437D: (0xCCCC0101, 'Did I say I'd fight the Djinn? I was\nonly joking! Anyway, thanks for\ndefeating him for us!'),
    0xF437E: (0xCCCC0101, 'Thank you! I'll do my best to serve the king\nand Princess Sara again!'),
    0xF437F: (0xCCCC0101, 'Thank you!\nI never would have thought Princess\nSara's ring had such power!'),
    0xF4380: (0xCCCC0101, 'We're back to our old selves!\nWe will do everything we can to protect Sasune\nfrom any curses from now on!'),
    0xF4381: (0xCCCC0101, 'Thank you, Warriors of the Light!\nYou've saved us all!'),
    0xF4386: (0xCCCC0101, 'Sir %shuyaku4%!\nThe king has been worrying about you since\nyou left.'),
    0xF4387: (0xCCCC0101, 'Sir %shuyaku4%!\nDo not worry about Princess Sara. We\nwill protect her with our lives!'),
    0xF4388: (0xCCCC0101, '%shuyaku4%...\nEver since we were little, you had always\nbested me...'),
    0xF4389: (0xCCCC0101, 'Red mages are warriors who have mastered\nboth the way of the sword and magic. Every\nsoldier in Sasune aspires to become one.'),
    0xF4437: (0xCCCC0101, 'Castle Sasune'),
    0x995D55: (0xCCCC0101, 'Atop the eastern tower is Lady Sara's\nquarters. I endeavor to keep it spotless\nuntil the day she returns.'),
    0x995D56: (0xCCCC0101, 'I believe that she would not be adverse\nto you entering, Sir %shuyaku4%.'),
    0x99D159: (0xCCCC0101, 'Atop the eastern tower is Lady Sara's\nquarters. She came back in tears, and\nwould not open the door for anyone...'),
    0x99D15A: (0xCCCC0101, 'However... Sir %shuyaku4%, she may let\nyou through. Would you go see if she\nis all right?'),
    0x99D15B: (0xCCCC0101, 'Thank you, Sir %shuyaku4%.\nI will look after Lady Sara until\nyou return.'),
    0x99D34D: (0xCCCC0101, 'If you want to exchange the front and back rows of\nyour party...'),
    0x99D34E: (0xCCCC0101, '...just select the same character twice.'),
    0x99D3B1: (0xCCCC0101, 'If you fancy changing the order of your party, just\nselect the two characters whose positions you'd\nlike to swap.'),
    0x131F0B5: (0xCCCC0101, 'A terrible curse had befallen the people in\nCastle Sasune while I was gone...'),
    0x131F0B5: (0xCCCC0101, 'A terrible curse had befallen the people in\nCastle Sasune while I was gone...'),
    0x131F0B6: (0xCCCC0101, 'Only the power of a mythril ring may save\nthem, I am told... But Kazus is suffering from\nthe same fate as Sasune...'),
    0x131F0B6: (0xCCCC0101, 'Only the power of a mythril ring may save\nthem, I am told... But Kazus is suffering from\nthe same fate as Sasune...'),
    0x131F0B7: (0xCCCC0101, 'I must do something, but... Where will I find\na mythril ring...?'),
    0x131F0B7: (0xCCCC0101, 'I must do something, but... Where will I find\na mythril ring...?'),
    0x131F0B8: (0xCCCC0101, '  %shuyaku3%\nI am the daughter of the blacksmith of Kazus. The\nking must still have the ring my father made him!'),
    0x131F0BB: (0xCCCC0101, '  %shuyaku2%\nWe've come to borrow the king's mythril ring to\nsave Kazus. Will you let us through?'),
    0x131F0BC: (0xCCCC0101, 'An audience with the king... Yes, I believe I can\narrange that. Come, I will be waiting in the throne\nroom.'),
    0x13265E5: (0xCCCC0101, '  Princess Sara\nEveryone!\n%shuyaku4%...!'),
    0x13265E6: (0xCCCC0101, '  %shuyaku4%\nLady Sara...\nI am glad to see you are safe.'),
    0x13265E7: (0xCCCC0101, '  Princess Sara\nNow we must cleanse the ring in the blessed\nspring, and that should lift the curse.'),
    0x13265EA: (0xCCCC0101, 'The blessed spring flows below Castle\nSasune. Let us hurry inside!'),
    0x1326775: (0xCCCC0101, 'Everyone!!!'),
    0x1326776: (0xCCCC0101, '  %shuyaku2%\nIt's Lady Sara!'),
    0x1326777: (0xCCCC0101, '  Princess Sara\nEveryone, be safe! Promise me you'll come\nback to Sasune when your duty is done!'),
    0x1326778: (0xCCCC0101, '  %shuyaku4%\nFear not! Our word is our bond!\nWe shall return!'),
    0x1CAFC65: (0xCCCC0101, '  Princess Sara\nThe blessed spring flows below Castle\nSasune. Let us hurry inside!'),
    0x1CAFC65: (0xCCCC0101, '  Princess Sara\nThe blessed spring flows below Castle\nSasune. Let us hurry inside!'),
}