items = {
    0xF437C: (0xCCCC0101, 'Thank you, Warriors of the Light!\nThe curse is gone!'),
    0xF4384: (0xCCCC0101, 'I wonder if the earthquake had anything to\ndo with the Djinn's seal breaking...'),
    0xF4385: (0xCCCC0101, 'A ship that can fly... Just who is this\nCid guy, and how could he build something\nlike that?'),
    0x995A35: (0xCCCC0101, 'The sword Wightslayer, the bane of all undead,\nis stored atop the western tower.'),
    0x995A99: (0xCCCC0101, 'The Sealed Cave is guarded by undead\nanimated by the power of darkness. You\nmust know that Cure is harmful to them.'),
    0x995C8D: (0xCCCC0101, '  King Sasune\nThere is a secret passageway in the Sealed\nCave... Search for the skeleton...key.'),
    0x995C8E: (0xCCCC0101, 'I am counting on you and your friends,\n%shuyaku4%. Banish the Djinn, and save\nus all!'),
    0x99CF65: (0xCCCC0101, 'The sword Wightslayer, the bane of all undead,\nis stored atop the western tower.'),
    0x99D091: (0xCCCC0101, '  King Sasune\nNow go forth on your journey--and may you\nreturn safely once you have fulfilled your task!'),
    0x131F119: (0xCCCC0101, '  King Sasune\nThe Djinn's curse has befallen us all...\nAnd I am no exception...'),
    0x131F11A: (0xCCCC0101, 'Sire, these younglings have come seeking the\nmythril ring to counter the curse.'),
    0x131F11B: (0xCCCC0101, '  King Sasune\nThe mythril ring... You seek to use its powers\nto banish the Djinn once again.'),
    0x131F11C: (0xCCCC0101, 'I would grant you this boon... However, my\ndaughter holds the ring, and she went missing\nshortly before the curse was cast upon us.'),
    0x131F11D: (0xCCCC0101, 'If the princess holds the ring, the Djinn may\nhave taken her!'),
    0x131F11E: (0xCCCC0101, '  King Sasune\nIf it is so... I fear for my precious Sara. The Djinn\nmust have taken her to its cave to the north.'),
    0x131F11F: (0xCCCC0101, '  %shuyaku1%\nDon't worry, sir, we'll get her back!'),
    0x131F120: (0xCCCC0101, 'Sire. I would like to ask you for your leave to\naccompany these brave souls to the Sealed\nCave, and rescue Lady Sara.'),
    0x131F121: (0xCCCC0101, '  King Sasune\nYou have my leave, %shuyaku4%.\nUnless...there are any objections?'),
    0x131F122: (0xCCCC0101, '  King Sasune\nThere is a secret passageway in the Sealed\nCave... Search for the skeleton...key.'),
    0x131F123: (0xCCCC0101, 'I am counting on you and your friends,\n%shuyaku4%. Banish the Djinn, and save\nus all!'),
    0x131F124: (0xCCCC0101, '  %shuyaku3%\nOf course not! His sword is worth twice\nthat of these two.'),
    0x131F125: (0xCCCC0101, '  %shuyaku1%\nNow, that's not fair! But...I agree that having one\nof the king's men with us would help us a lot.'),
    0x131F126: (0xCCCC0101, '  %shuyaku4% has joined the party!'),
    0x13266AD: (0xCCCC0101, '  King Sasune\nYou have returned! Your courageous deeds have\nsaved the kingdom! You have my deepest gratitude!'),
    0x13266AE: (0xCCCC0101, '   %shuyaku1%\nThank you, sire...but we must go. We've\nbeen chosen to be the Warriors of the Light.'),
    0x13266AF: (0xCCCC0101, '  King Sasune\nWarriors of the Light, you say!?\n%shuyaku4%, are you leaving as well?'),
    0x13266B0: (0xCCCC0101, '  %shuyaku4%\nYes, sire...'),
    0x13266B1: (0xCCCC0101, '  King Sasune\nI see... Then I bid you all well. Know that our\nhopes go with you, young champions!'),
    0x13266B2: (0xCCCC0101, ' "Yes, sire!"'),
    0x13266B5: (0xCCCC0101, '  King Sasune\nTake this with you. It will surely prove itself\nuseful during your journey.'),
    0x13266B6: (0xCCCC0101, '  King Sasune presents you with a magical\n  folding canoe!'),
}