items = {
    0x9A6D99: (0xCCCC0101, '  Jolina\nMy daughter, Salina, has fallen in love with that\nvagrant, Desch.'),
    0x9A6D9A: (0xCCCC0101, 'But he didn't stay a fortnight before he left,\nmumbling about some task he'd promised himself to\ndo. And Salina's been angsty and crying ever since.'),
    0x9A6D9C: (0xCCCC0101, '  Jolina\n...Desch!? Where have you been?\nSalina's been worried sick about you!'),
    0x9A6D9D: (0xCCCC0101, 'I know you can't come back here until you've\ndone whatever it is you've set your mind to\ndo...but promise me that you will come back.'),
    0x9A6D9E: (0xCCCC0101, '  Jolina\nWhere's that cadger Desch gone off to?\nMy Salina's been waiting for him for weeks!'),
    0x9A6DFD: (0xCCCC0101, '  Salina\n*Sob* ...Oh, Desch, my beloved Desch!\nWhen will you be back?'),
    0x9A6DFE: (0xCCCC0101, 'Why would you go to the mountains in the east,\nwhere a dragon is said to dwell? And what would\ndrive you to go to such a place alone?'),
    0x9A6DFF: (0xCCCC0101, '  %shuyaku3%\nDefinitely! Let's go look for this Desch guy\nand bring him back here!'),
    0x9A6E00: (0xCCCC0101, '  Salina\nDesch! Oh, Desch! You've come back!\nI was certain you had forgotten about me!'),
    0x9A6E01: (0xCCCC0101, 'I'm relieved to see you're all right.\nI'll stop crying, and wait for your return once\nmore.'),
    0x9A6E03: (0xCCCC0101, '  %shuyaku1%\nHey, do you think we should check out this\ndragon mountain?'),
    0x9E177D: (0xCCCC0101, '  Salina\nWhat...? Desch...in the Tower of Owen...?'),
    0x9E177E: (0xCCCC0101, '  %shuyaku3%\nI...I'm sure he'll be back soon...'),
    0x9E177F: (0xCCCC0101, '  Salina\nOh, Desch... My love...\nPlease, come back to me safe...'),
    0x1CB9A99: (0xCCCC0101, '  Desch\nSorry I dragged you all into this... But thanks to\nyou, I've been able to satisfy my curiosity!'),
    0x1CB9A9A: (0xCCCC0101, '  %shuyaku3%\nJust finish whatever you need to do and go see\nSalina! She's been waiting for you all this time!'),
}