items = {
    0xF4254: (0xCCCC0101, 'Why, hello there!\nI'm a dancer! Watch me prance!'),
    0xF443B: (0xCCCC0101, 'Canaan'),
    0xF443B: (0xCCCC0101, 'Canaan'),
    0x9A6BA5: (0xCCCC0101, 'I heard that a traveling mage hid a magical healing\nsolution somewhere in this town a long time ago.'),
    0x9A6C09: (0xCCCC0101, 'Rumor has it that there's a gnome village hidden\nsomewhere in the woods south of here.'),
    0x9A6C6D: (0xCCCC0101, 'That young lad Desch bought the last Mini scroll\noff me. What does that spell do? It shrinks you\nto gnomish size, that's what it does!'),
    0x9A6CD1: (0xCCCC0101, 'Aero is a white magic spell that harnesses the\npowers of wind to damage the enemy. Flying\nmonsters are especially vulnerable to it.'),
    0x9A6D35: (0xCCCC0101, 'Why, hello there. We don't usually get this many\nvisitors around here. The last one we had was a\nyoung man named Desch.'),
    0x9A6F29: (0xCCCC0101, 'If you want to rearrange your inventory in the menu\nscreen...'),
    0x9A6F2A: (0xCCCC0101, 'You need do no more than pick the two items\nwhose placement you'd like to change.'),
    0x9A6F8D: (0xCCCC0101, 'You might see arrows pointing left and right on the\nbottom of the menu screen.'),
    0x9A6F8E: (0xCCCC0101, 'You can flip between screens by using\n%s and %s.'),
    0x9E1525: (0xCCCC0101, 'I heard that a traveling mage hid a magical healing\nsolution somewhere in this town a long time ago.'),
    0x9E1589: (0xCCCC0101, 'Rumor has it that there's a gnome village hidden\nsomewhere in the woods south of here.'),
    0x9E15ED: (0xCCCC0101, 'That young lad Desch bought the last Mini scroll\noff me. What does that spell do? It shrinks you\nto gnomish size, is what it does!'),
    0x9E1651: (0xCCCC0101, 'Aero is a white magic spell that harnesses the\npowers of wind to damage the enemy. Flying\nmonsters are especially vulnerable to it.'),
    0x9E16B5: (0xCCCC0101, 'Why, hello there. We don't usually get this many\nvisitors around here. The last one we had was a\nyoung man named Desch.'),
    0x9E16B6: (0xCCCC0101, 'He was really close with Salina...\nI wonder when he'll be back.'),
    0x1330225: (0xCCCC0101, '  Cid\nThank you for your help, lads! Let me know if\nthere's anything I can do to help you out!'),
    0x1330226: (0xCCCC0101, 'I know! You'd probably want to get your hands on\na new airship--well, I'm the man for the job!'),
    0x1330227: (0xCCCC0101, 'But you'll have to meet King Argus, first. See, I\nonly made the airship's hull. The king's the one\nwho knows the secret of creating airship engines.'),
    0x1330228: (0xCCCC0101, 'Come see me again once you've spoken with King\nArgus!'),
    0x133022B: (0xCCCC0101, '  Cid has left the party.'),
    0x136D2B8: (0xCCCC0101, '  Cid\nI hope they reached the surface all right...'),
    0x136D2B9: (0xCCCC0101, 'Warriors of the Light... You lads are our last\nhope!'),
    0x13CA0AF: (0xCCCC0101, '  Cid\nOh! I've missed you so!'),
    0x13CA0B0: (0xCCCC0101, 'Oh, my! Cid, stop it! People are watching!'),
    0x13CA0B1: (0xCCCC0101, '  Desch\nSalina!'),
    0x13CA0B2: (0xCCCC0101, '  Salina\nDesch! You're back! Promise me you won't\nleave ever again!'),
    0x13CA0B3: (0xCCCC0101, '  Desch\nI promise!'),
    0x13CA0B4: (0xCCCC0101, '  Cid\nHaw! We can't be outdone by those\nyoung'uns, can we?'),
    0x13CA0B5: (0xCCCC0101, 'Cid! Stop, I say...! Oh, Cid, must you be so\ninappropriate...?'),
    0x13CA0B6: (0xCCCC0101, '  %shuyaku3%\nAhem... Umm...'),
    0x13CA0B7: (0xCCCC0101, '  Desch\nOh! Sorry. Got carried away there.'),
    0x13CA0B8: (0xCCCC0101, '  Cid\nAhem... I guess I did, too.'),
    0x13CA0B9: (0xCCCC0101, '  Desch\nHey! Don't forget to come get me if you're\ngoing adventuring again!'),
    0x13CA0BA: (0xCCCC0101, '  Salina\nYou're not going anywhere, Desch!'),
    0x13CA0BB: (0xCCCC0101, '  %shuyaku1%\nLooks like you're not getting out of this one,\nDesch!'),
    0x13CA0BC: (0xCCCC0101, '  Desch\nYeah, yeah.'),
    0x13CA0BD: (0xCCCC0101, '  Cid\nCome visit us anytime, hear?\nYou have to sample Mrs. Cid's dinner special!'),
    0x13CA0BE: (0xCCCC0101, '  %shuyaku3%\nThank you, but I have to go see my father\nfirst...'),
    0x13CA0BF: (0xCCCC0101, 'And I have to train to be a good smith...\nIt's the least I can do to thank him for\nraising me, you know.'),
    0x13CA0C0: (0xCCCC0101, '  Cid\nGood, I'm sure Takka will be happy to hear\nthat! Give him my regards, hear?'),
    0x13CA0C1: (0xCCCC0101, '  %shuyaku1%\nCid, Desch, we'll see you soon!'),
    0x13CA0C2: (0xCCCC0101, '  %shuyaku4%\nMilady, let us return to Castle Sasune.'),
    0x13CA0C3: (0xCCCC0101, '  Princess Sara\nNo! I do not want to go back so soon!'),
    0x13CA0C4: (0xCCCC0101, '  %shuyaku4%\nMilady! Why...?'),
    0x13CA0C5: (0xCCCC0101, '  Princess Sara\nMen are so obtuse... Must I say it plainly?\nI want to stay with you a bit longer! There!'),
    0x13CA0C6: (0xCCCC0101, '  %shuyaku4%\n...'),
    0x13CA0C7: (0xCCCC0101, '  Princess Sara\nDon't look so surprised! Come, let us visit\nKazus and Ur first.'),
    0x13CA0C8: (0xCCCC0101, '  %shuyaku4%\nAs you wish, Milady. I will stay by your side\nuntil the end of time!'),
}