items = {
    0xF438B: (0xCCCC0101, 'Take good care of the Enterprise, all right?'),
    0xF438C: (0xCCCC0101, 'We vikings are warriors of the sea! We might\nbe a bit slow, but I guarantee you that we're\ncertified axe masters!'),
    0xF443E: (0xCCCC0101, 'Vikings' Cove'),
    0x9B0975: (0xCCCC0101, 'I-I'm not hiding, honest!\nI'm just waiting for Pops to come.'),
    0x9B09D9: (0xCCCC0101, 'The Enterprise is a fine ship...but no one wants\nto board it as long as that sea dragon's lurking\nin the nearby waters.'),
    0x9B0AA1: (0xCCCC0101, 'Don't get on a boat if you value your life!\nThe sea dragon attacks any ships that come\nnear the cape!'),
    0x9B0AA2: (0xCCCC0101, 'It must be the Nepto Dragon...the great serpent\nfor which the Nepto Temple was built!'),
    0x9B0B05: (0xCCCC0101, 'That's the boss down there. Hmph! What is\nit with men? You lose a few ships and you\nact like you got the pink slip from Valhalla!'),
    0x9B0BCD: (0xCCCC0101, 'Rid us of that sea dragon, and the Enterprise\nis yours to take.'),
    0x9B0BCE: (0xCCCC0101, 'If you fail... Well, I guess you'll just be another\noffering to the Nepto Temple, huh.'),
    0x9B58C1: (0xCCCC0101, 'You guys are great!\nI'll name my children after you!'),
    0x9B5925: (0xCCCC0101, 'I'm glad to see you made it back safely.\nAs you might've guessed, the boss is in a\nbetter mood now.'),
    0x1339E65: (0xCCCC0101, 'Yes, I run things around here...'),
    0x1339E66: (0xCCCC0101, 'There hasn't been much to run since\nthat sea dragon appeared and destroyed\nmost of our ships, though...'),
    0x1339E67: (0xCCCC0101, 'You look like capable adventurers... If you\nmanage to defeat the dragon, our best\nship, the Enterprise, is yours!'),
    0x1339E68: (0xCCCC0101, '  %shuyaku1%\nReally? Promise?'),
    0x1339E69: (0xCCCC0101, 'Promise--viking's honor!\n...If you manage to make it back, that is.'),
    0x133ED4D: (0xCCCC0101, 'Welcome back! The vikings will never forget\nwhat you have done for us this day!'),
    0x133ED4D: (0xCCCC0101, 'Welcome back! The vikings will never forget\nwhat you have done for us this day!'),
    0x133ED4E: (0xCCCC0101, 'As promised, the Enterprise is yours.\nTake it and sail forth, young heroes.\nMay the wind guide you!'),
    0x133ED4E: (0xCCCC0101, 'As promised, the Enterprise is yours.\nTake it and sail forth, young heroes.\nMay the wind guide you!'),
    0x133ED4F: (0xCCCC0101, '  You are now the proud owner of the\n  Enterprise!'),
    0x1CC8305: (0xCCCC0101, '  Desch\nWe did it! We've got our own ship! Now we can go\nto exotic ports, and meet even more exotic women!'),
    0x1CC8306: (0xCCCC0101, '  %shuyaku3%\nWhat!? I can't believe you! I knew I was right\nwhen I told Salina to forget about you! Oooh!'),
    0x1CC8307: (0xCCCC0101, '  Desch\nHey! I was just kidding!\nYeesh, talk about touchy...'),
}