items = {
    0xF4240: (0xCCCC0101, '  Not finished yet.'),
    0xF4395: (0xCCCC0101, 'Slowly, the village is recovering. It wouldn't have\nbeen possible without your help.'),
    0xF4399: (0xCCCC0101, 'You've saved us!\nThank you!'),
    0xF439B: (0xCCCC0101, 'You truly saved us all.\nI thank you from the bottom of my heart.'),
    0xF439B: (0xCCCC0101, 'You truly saved us all.\nI thank you from the bottom of my heart.'),
    0x9B7F6D: (0xCCCC0101, 'This is the abode of the Elder of Tokkul.\nPlease, you must speak with him.'),
    0x9B7FD1: (0xCCCC0101, 'There is a hidden stairway inside the fireplace.\nWe've stored weapons in the basement, but\nnone of us are strong enough to use them.'),
    0x9B7FD2: (0xCCCC0101, 'Please, take them... Take the weapons, and save\nour town!'),
    0x1341395: (0xCCCC0101, 'So you are the strangers. I am the Elder of Tokkul.\nYou must have heard by now about the soldiers\nwho pillaged our town.'),
    0x1341395: (0xCCCC0101, 'So you are the strangers. I am the Elder of Tokkul.\nYou must have heard by now about the soldiers\nwho pillaged our town.'),
    0x1341395: (0xCCCC0101, 'So you are the strangers. I am the Elder of Tokkul.\nYou must have heard by now about the soldiers\nwho pillaged our town.'),
    0x1341395: (0xCCCC0101, 'So you are the strangers. I am the Elder of Tokkul.\nYou must have heard by now about the soldiers\nwho pillaged our town.'),
    0x1341395: (0xCCCC0101, 'So you are the strangers. I am the Elder of Tokkul.\nYou must have heard by now about the soldiers\nwho pillaged our town.'),
    0x1341396: (0xCCCC0101, 'They suddenly appeared after the earthquake, from\nthe desert to the west. They took away our grain,\nour water, and any able-bodied townsfolk...'),
    0x1341396: (0xCCCC0101, 'They suddenly appeared after the earthquake, from\nthe desert to the west. They took away our grain,\nour water, and any able-bodied townsfolk...'),
    0x1341396: (0xCCCC0101, 'They suddenly appeared after the earthquake, from\nthe desert to the west. They took away our grain,\nour water, and any able-bodied townsfolk...'),
    0x1341396: (0xCCCC0101, 'They suddenly appeared after the earthquake, from\nthe desert to the west. They took away our grain,\nour water, and any able-bodied townsfolk...'),
    0x1341396: (0xCCCC0101, 'They suddenly appeared after the earthquake, from\nthe desert to the west. They took away our grain,\nour water, and any able-bodied townsfolk...'),
    0x1341397: (0xCCCC0101, 'You have seen the result of their attacks...\nThere is nothing we can do...'),
    0x1341397: (0xCCCC0101, 'You have seen the result of their attacks...\nThere is nothing we can do...'),
    0x1341397: (0xCCCC0101, 'You have seen the result of their attacks...\nThere is nothing we can do...'),
    0x1341397: (0xCCCC0101, 'You have seen the result of their attacks...\nThere is nothing we can do...'),
    0x1341397: (0xCCCC0101, 'You have seen the result of their attacks...\nThere is nothing we can do...'),
}