items = {
    0xF4396: (0xCCCC0101, 'My son came back!\nI don't know how to thank you!'),
    0xF4397: (0xCCCC0101, 'King Argus and a princess from a faraway\nland promised us they would help rebuild\nthis village!'),
    0xF4398: (0xCCCC0101, 'You want to know about crystals? Maybe\nsomeone in the Village of the Ancients\nto the west knows something about them. '),
    0xF4398: (0xCCCC0101, 'You want to know about crystals? Maybe\nsomeone in the Village of the Ancients\nto the west knows something about them. '),
    0xF4399: (0xCCCC0101, 'You've saved us!\nThank you!'),
    0xF439A: (0xCCCC0101, 'Wow! You're the one who beat Hein!\nCan I have your autograph?'),
    0xF439B: (0xCCCC0101, 'You truly saved us all.\nI thank you from the bottom of my heart.'),
    0xF443F: (0xCCCC0101, 'Tokkul'),
    0x9B7D15: (0xCCCC0101, 'No! Go away! I have nothing you want!'),
    0x9B7D79: (0xCCCC0101, 'P-please... I beg you, do not kill me...!'),
    0x9B7DDD: (0xCCCC0101, 'There be a demon in the sands to the west...\nI have seen it! A tree! A giant tree that moves!'),
    0x9B7EA5: (0xCCCC0101, 'Far to the west, across the desert, is a\nvillage...a village of people who claim to\nbe descendants of the Ancients.'),
    0x9B7EA5: (0xCCCC0101, 'Far to the west, across the desert, is a\nvillage...a village of people who claim to\nbe descendants of the Ancients.'),
    0x9B8035: (0xCCCC0101, 'The settlement in the mountains west of\nCastle Argus is said to be inhabited by people\nwho can see into the future!'),
    0x1360F65: (0xCCCC0101, '  You can't move!'),
    0x1360F66: (0xCCCC0101, '"Hey!"\n"What's going on!?"\n"What is the meaning of this!?"'),
    0x1360F67: (0xCCCC0101, 'Get them!'),
    0x1360F68: (0xCCCC0101, 'Take them away to Castle Hein!\nThey'll make good slaves!'),
    0x1CCAA15: (0xCCCC0101, '  Desch\nThose soldiers've made a real mess of this town,\nthat's for sure.'),
    0x1CCAA16: (0xCCCC0101, '  %shuyaku4%\nBut can they truly be King Argus's men? I cannot\nbelieve the king would order such heinous acts...'),
    0x1CCAA17: (0xCCCC0101, '  %shuyaku2%\nThe soldiers' attacks began after the earthquake...\nMaybe the two are connected, somehow.'),
}