items = {
    0xF4245: (0xCCCC0101, '  %lead_player_name%\nAhhh... I slept like a log!'),
    0xF4245: (0xCCCC0101, '  %lead_player_name%\nAhhh... I slept like a log!'),
    0xF4245: (0xCCCC0101, '  %lead_player_name%\nAhhh... I slept like a log!'),
    0xF4246: (0xCCCC0101, '  HP and MP restored.'),
    0xF4246: (0xCCCC0101, '  HP and MP restored.'),
    0xF4246: (0xCCCC0101, '  HP and MP restored.'),
    0xF4A11: (0xCCCC0101, 'Oh! I see you have a master freelancer\namong you.\nHere, you should have this insignia.'),
    0xF4A12: (0xCCCC0101, 'Oh! I see you have a master onion knight\namong you.\nHere, you should have this insignia.'),
    0xF4A13: (0xCCCC0101, 'Oh! I see you have a master warrior\namong you.\nHere, you should have this insignia.'),
    0xF4A14: (0xCCCC0101, 'Oh! I see you have a master monk\namong you.\nHere, you should have this insignia.'),
    0xF4A15: (0xCCCC0101, 'Oh! I see you have a master white mage\namong you.\nHere, you should have this insignia.'),
    0xF4A16: (0xCCCC0101, 'Oh! I see you have a master black mage\namong you.\nHere, you should have this insignia.'),
    0xF4A17: (0xCCCC0101, 'Oh! I see you have a master red mage\namong you.\nHere, you should have this insignia.'),
    0xF4A18: (0xCCCC0101, 'Oh! I see you have a master ranger\namong you.\nHere, you should have this insignia.'),
    0xF4A19: (0xCCCC0101, 'Oh! I see you have a master knight\namong you.\nHere, you should have this insignia.'),
    0xF4A1A: (0xCCCC0101, 'Oh! I see you have a master thief\namong you.\nHere, you should have this insignia.'),
    0xF4A1B: (0xCCCC0101, 'Oh! I see you have a master scholar\namong you.\nHere, you should have this insignia.'),
    0xF4A1C: (0xCCCC0101, 'Oh! I see you have a master geomancer\namong you.\nHere, you should have this insignia.'),
    0xF4A1D: (0xCCCC0101, 'Oh! I see you have a master dragoon\namong you.\nHere, you should have this insignia.'),
    0xF4A1E: (0xCCCC0101, 'Oh! I see you have a master viking\namong you.\nHere, you should have this insignia.'),
    0xF4A1F: (0xCCCC0101, 'Oh! I see you have a master dark knight\namong you.\nHere, you should have this insignia.'),
    0xF4A20: (0xCCCC0101, 'Oh! I see you have a master evoker\namong you.\nHere, you should have this insignia.'),
    0xF4A21: (0xCCCC0101, 'Oh! I see you have a master bard\namong you.\nHere, you should have this insignia.'),
    0xF4A22: (0xCCCC0101, 'Oh! I see you have a master black belt\namong you.\nHere, you should have this insignia.'),
    0xF4A23: (0xCCCC0101, 'Oh! I see you have a master devout\namong you.\nHere, you should have this insignia.'),
    0xF4A24: (0xCCCC0101, 'Oh! I see you have a master magus\namong you.\nHere, you should have this insignia.'),
    0xF4A25: (0xCCCC0101, 'Oh! I see you have a master summoner\namong you.\nHere, you should have this insignia.'),
    0xF4A26: (0xCCCC0101, 'Oh! I see you have a master sage\namong you.\nHere, you should have this insignia.'),
    0xF4A27: (0xCCCC0101, 'Oh! I see you have a master ninja\namong you.\nHere, you should have this insignia.'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A2E: (0xCCCC0101, 'In addition, I will give this to you in praise\nof your achievements!'),
    0xF4A75: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster freelancer in your possession.\nHere, you should have this.'),
    0xF4A76: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster onion knight in your possession.\nHere, you should have this.'),
    0xF4A77: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster warrior in your possession.\nHere, you should have this.'),
    0xF4A78: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster monk in your possession.\nHere, you should have this.'),
    0xF4A79: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster white mage in your possession.\nHere, you should have this.'),
    0xF4A7A: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster black mage in your possession.\nHere, you should have this.'),
    0xF4A7B: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster red mage in your possession.\nHere, you should have this.'),
    0xF4A7C: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster ranger in your possession.\nHere, you should have this.'),
    0xF4A7D: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster knight in your possession.\nHere, you should have this.'),
    0xF4A7E: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster thief in your possession.\nHere, you should have this.'),
    0xF4A7F: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster scholar in your possession.\nHere, you should have this.'),
    0xF4A80: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster geomancer in your possession.\nHere, you should have this.'),
    0xF4A81: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster dragoon in your possession.\nHere, you should have this.'),
    0xF4A82: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster viking in your possession.\nHere, you should have this.'),
    0xF4A83: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster dark knight in your possession.\nHere, you should have this.'),
    0xF4A84: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster evoker in your possession.\nHere, you should have this.'),
    0xF4A85: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster bard in your possession.\nHere, you should have this.'),
    0xF4A86: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster black belt in your possession.\nHere, you should have this.'),
    0xF4A87: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster devout in your possession.\nHere, you should have this.'),
    0xF4A88: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster magus in your possession.\nHere, you should have this.'),
    0xF4A89: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster summoner in your possession.\nHere, you should have this.'),
    0xF4A8A: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster sage in your possession.\nHere, you should have this.'),
    0xF4A8B: (0xCCCC0101, 'Oh! I see you have a letter from a\nmaster ninja in your possession.\nHere, you should have this.'),
    0xF4A92: (0xCCCC0101, 'I will now continue my travels, seeking new\nmetals to temper and all that... Maybe we'll\nmeet again somewhere.'),
    0xF4A9C: (0xCCCC0101, 'I am a wandering smith.'),
    0xF4A9D: (0xCCCC0101, 'If any one of you has mastered a job...'),
    0xF4A9E: (0xCCCC0101, 'I will forge you special weapons and armor\nusable only by that job.'),
    0xF4A9F: (0xCCCC0101, 'I will now continue my travels, seeking new\nmetals to temper and all that... Maybe we'll\nmeet again somewhere.'),
    0xF4AD9: (0xCCCC0101, '  Obtained Freelancer Card.'),
    0xF4ADA: (0xCCCC0101, '  Obtained Onion Knight Card.'),
    0xF4ADB: (0xCCCC0101, '  Obtained Warrior Card.'),
    0xF4ADC: (0xCCCC0101, '  Obtained Monk Card.'),
    0xF4ADD: (0xCCCC0101, '  Obtained White Mage Card.'),
    0xF4ADE: (0xCCCC0101, '  Obtained Black Mage Card.'),
    0xF4ADF: (0xCCCC0101, '  Obtained Red Mage Card.'),
    0xF4AE0: (0xCCCC0101, '  Obtained Ranger Card.'),
    0xF4AE1: (0xCCCC0101, '  Obtained Knight Card.'),
    0xF4AE2: (0xCCCC0101, '  Obtained Thief Card.'),
    0xF4AE3: (0xCCCC0101, '  Obtained Scholar Card.'),
    0xF4AE4: (0xCCCC0101, '  Obtained Geomancer Card.'),
    0xF4AE5: (0xCCCC0101, '  Obtained Dragoon Card.'),
    0xF4AE6: (0xCCCC0101, '  Obtained Viking Card.'),
    0xF4AE7: (0xCCCC0101, '  Obtained Dark Knight Card.'),
    0xF4AE8: (0xCCCC0101, '  Obtained Evoker Card.'),
    0xF4AE9: (0xCCCC0101, '  Obtained Bard Card.'),
    0xF4AEA: (0xCCCC0101, '  Obtained Black Belt Card.'),
    0xF4AEB: (0xCCCC0101, '  Obtained Devout Card.'),
    0xF4AEC: (0xCCCC0101, '  Obtained Magus Card.'),
    0xF4AED: (0xCCCC0101, '  Obtained Summoner Card.'),
    0xF4AEE: (0xCCCC0101, '  Obtained Sage Card.'),
    0xF4AEF: (0xCCCC0101, '  Obtained Ninja Card.'),
    0xF4B3D: (0xCCCC0101, '  Obtained Celestial Gloves.'),
    0xF4B3E: (0xCCCC0101, '  Obtained Onion Blade.'),
    0xF4B3F: (0xCCCC0101, '  Obtained Gigantic Axe.'),
    0xF4B40: (0xCCCC0101, '  Obtained Shura Gloves.'),
    0xF4B41: (0xCCCC0101, '  Obtained Angel Robe.'),
    0xF4B42: (0xCCCC0101, '  Obtained Lilith Rod.'),
    0xF4B43: (0xCCCC0101, '  Obtained Crimson Vest.'),
    0xF4B44: (0xCCCC0101, '  Obtained Artemis Bow.'),
    0xF4B45: (0xCCCC0101, '  Obtained Save the Queen.'),
    0xF4B46: (0xCCCC0101, '  Obtained Gladius.'),
    0xF4B47: (0xCCCC0101, '  Obtained Omnitome.'),
    0xF4B48: (0xCCCC0101, '  Obtained Blessed Bell.'),
    0xF4B49: (0xCCCC0101, '  Obtained Magic Lance.'),
    0xF4B4A: (0xCCCC0101, '  Obtained Mighty Hammer.'),
    0xF4B4B: (0xCCCC0101, '  Obtained Murakumo.'),
    0xF4B4C: (0xCCCC0101, '  Obtained Royal Crown.'),
    0xF4B4D: (0xCCCC0101, '  Obtained Ballad Crown.'),
    0xF4B4E: (0xCCCC0101, '  Obtained Master Dogi.'),
    0xF4B4F: (0xCCCC0101, '  Obtained Holy Wand.'),
    0xF4B50: (0xCCCC0101, '  Obtained Millennium Rod.'),
    0xF4B51: (0xCCCC0101, '  Obtained Astral Bracers.'),
    0xF4B52: (0xCCCC0101, '  Obtained Sage Staff.'),
    0xF4B53: (0xCCCC0101, '  Obtained Muramasa.'),
}