items = {
    0xF4440: (0xCCCC0101, 'Village of the Ancients'),
    0x9BA425: (0xCCCC0101, 'We are the sons and daughters of the Ancients,\na once great civilization... But now we live by the\nland, as our Rule commands.'),
    0x9BA426: (0xCCCC0101, 'Long ago, our Rule also charged us with guarding the\nTower of Owen.'),
    0x9BA489: (0xCCCC0101, 'Our ancestors once built a great civilization...but\nwere punished for their arrogance. That is the\ncatastrophe we now call the Wrath of the Light.'),
    0x9BA48A: (0xCCCC0101, 'They attempted to harness the power of the light.\nThey arrogantly assumed there was nothing they\ncould not do... But they had thought wrong.'),
    0x9BA48B: (0xCCCC0101, 'It is said that four warriors emerged from the world\nof darkness, and stopped the destructive forces\nof light that our ancestors had conjured...'),
    0x9BA48C: (0xCCCC0101, '...But now, it is darkness that has emerged, bringing\nchaos and destruction in its wake. All that we can do\nis wait for the four warriors to appear once again.'),
    0x9BA4ED: (0xCCCC0101, 'Would you believe me if I told you that the ground\nwe're standing on--this continent--was aloft?\nRubbish, you say? Well, it's nonetheless true.'),
    0x9BA4EE: (0xCCCC0101, 'The Tower of Owen is a pillar. The pillar that\nsupports our continent, built by the Ancients\nto bring balance between light and darkness.'),
    0x9BA551: (0xCCCC0101, 'Our Rule commands us to let ourselves be guided\nby the Great Will.'),
    0x9BA5B5: (0xCCCC0101, 'Light and darkness have their own will. A will that\ntranscends that of mere mortals such as you and\nI. And they are perpetually at war.'),
    0x9BA5B6: (0xCCCC0101, 'The crystals exist to bring balance between these\ntwo forces.'),
    0x9BA5B7: (0xCCCC0101, 'When the balance tilts too far one way, the crystals\nchoose four mortals, and bless them with their\npower...'),
    0x9BA5B8: (0xCCCC0101, 'Now that the balance has tilted toward darkness,\nfour Warriors of the Light will be chosen, and tasked\nwith bringing equilibrium to the world once more.'),
    0x9BA619: (0xCCCC0101, 'Have you ever seen a chocobo? Such a strange bird\nit is... They make their home in the woods to the\neast, if you wish to see them.'),
    0x9BA67D: (0xCCCC0101, 'I'll give you a prize if you run around the edge of the\ncontinent on a chocobo!'),
    0x9BA6E1: (0xCCCC0101, 'In-kweh-dible! You actually did it!\nWell, good wark...I mean, work!\nHere's your prize!'),
    0x9BA6E2: (0xCCCC0101, '  Obtained Gnomish Bread!'),
    0x1CCD125: (0xCCCC0101, '  Desch\nThis village seems awfully familiar... All this talk\nabout light and darkness...'),
    0x1CCD126: (0xCCCC0101, '  Desch\nWha...? Hey!'),
    0x1CCD127: (0xCCCC0101, 'I remember! I remember now...'),
    0x1CCD128: (0xCCCC0101, 'The powers of darkness...they stopped the flow\nof time on the surface world.'),
    0x1CCD129: (0xCCCC0101, 'That's how this floating continent was born...'),
    0x1CCD12A: (0xCCCC0101, '  %shuyaku4%\nWhat gibberish is that? The floating continent\ntheorem was already hard to take in...'),
    0x1CCD12B: (0xCCCC0101, '  %shuyaku2%\nDo you mean there are other continents...aside from\nour own?'),
    0x1CCD12C: (0xCCCC0101, '  Desch\nI... I don't know. I feel so strange...'),
}