items = {
    0xF43A9: (0xCCCC0101, 'If darkness engulfs the world, everything will\nbe consumed by the Void...'),
    0xF43AA: (0xCCCC0101, 'When the balance between light and darkness\nis broken, it will give birth to an unstoppable force\nthat will destroy the world...'),
    0xF4442: (0xCCCC0101, 'Gulgan Gulch'),
    0x9BCB35: (0xCCCC0101, 'You are in Gulgan Gulch. We Gulgans are born\nsightless. However, we are endowed with the power\nof clairvoyance--we can glimpse into the future.'),
    0x9BCB99: (0xCCCC0101, 'The crystal that gave you your blessing is the\ncrystal of wind. You must go and seek the other\nthree: the crystals of fire, water, and earth.'),
    0x9BCBFD: (0xCCCC0101, 'The powers of darkness have hidden the light\nfrom the remaining crystals. And the crystals\nthemselves have chosen to seal their powers.'),
    0x9BCC61: (0xCCCC0101, 'The earthquake was only the beginning.\nThe great tremors that swallowed the crystals,\nthe light of our world...'),
    0x9BCC62: (0xCCCC0101, 'only to spawn monsters from the depths of\nthe scarred land, are nothing but harbingers\nof what is yet to come.'),
    0x9BCCC5: (0xCCCC0101, 'I sense the power of fire from the island of the\ndwarves...'),
    0x9BCD8D: (0xCCCC0101, 'When the tower begins to crumble, spewing flames\nof doom, is when the man who changes destinies\nwill awaken.'),
    0x9BCDF1: (0xCCCC0101, 'We live in this gulch, hidden from the world, for\noftentimes knowing the future leads to misfortune.'),
    0x9BCEB9: (0xCCCC0101, 'The living wood... The weeping trees are calling\nfor you.'),
    0x1CCF835: (0xCCCC0101, '  Desch\nI gotta go to the Tower of Owen... I can feel it.'),
    0x1CCF839: (0xCCCC0101, '  %shuyaku3%\nAre you absolutely completely certainly sure?\nI really have a bad feeling about this...'),
}