items = {
    0xF4441: (0xCCCC0101, 'Living Woods'),
    0x9BF245: (0xCCCC0101, 'We are faeries, keepers of these woods.'),
    0x9BF2A9: (0xCCCC0101, 'The wizard who took the elder can change his\nweak point at will. You will need to be able to\nanalyze him in order to defeat him.'),
    0x9BF30D: (0xCCCC0101, 'These woods are blessed with life.'),
    0x9BF371: (0xCCCC0101, 'The trees are weeping...\nThey weep for the missing Elder Tree--a tree that\nhas lived for ten thousand years.'),
    0x9BF372: (0xCCCC0101, 'A wizard came and put a curse on the elder,\nthen took him away...'),
    0x9BF3D5: (0xCCCC0101, 'If the Elder Tree does not return soon, these\nwoods will wither and die...'),
    0x9BF439: (0xCCCC0101, 'The Elder Tree was carved into the shape of\na castle, and wanders the desert aimlessly.\nYou must help the elder!'),
    0x9BF49D: (0xCCCC0101, 'The wizard Hein, of Castle Argus, is the one\nwho put the curse on the Elder Tree.'),
    0x9BF501: (0xCCCC0101, 'Hein changes his weak point when he uses\nBarrier Shift.'),
    0x1CD1F45: (0xCCCC0101, '  Desch\nFaeries...I've never seen anything like them\nbefore.'),
    0x1CD1F46: (0xCCCC0101, '  %shuyaku2%\nI got it!'),
    0x1CD1F47: (0xCCCC0101, 'The soldiers of Argus are being controlled by\nthe wizard Hein!'),
    0x1CD1F48: (0xCCCC0101, '  %shuyaku4%\nWhat could this malfeasant Hein be after,\nI wonder...?'),
}