items = {
    0x9BF245: (0xCCCC0101, 'We are faeries, keepers of these woods.'),
    0x9BF2A9: (0xCCCC0101, 'The wizard who took the elder can change his\nweak point at will. You will need to be able to\nanalyze him in order to defeat him.'),
    0x9BF30D: (0xCCCC0101, 'These woods are blessed with life.'),
    0x9BF371: (0xCCCC0101, 'The trees are weeping...\nThey weep for the missing Elder Tree--a tree that\nhas lived for ten thousand years.'),
    0x9BF3D5: (0xCCCC0101, 'If the Elder Tree does not return soon, these\nwoods will wither and die...'),
    0x9BF439: (0xCCCC0101, 'The Elder Tree was carved into the shape of\na castle, and wanders the desert aimlessly.\nYou must help the elder!'),
    0x9BF49D: (0xCCCC0101, 'The wizard Hein, of Castle Argus, is the one\nwho put the curse on the Elder Tree.'),
    0x9BF501: (0xCCCC0101, 'Hein changes his weak point when he uses\nBarrier Shift.'),
    0x1365DE9: (0xCCCC0101, 'I am back where I belong...\nThank you for your help, young ones.'),
    0x1365DEA: (0xCCCC0101, 'Here, take this. Use it when the power of\ndarkness stands in your way.'),
    0x1365DEB: (0xCCCC0101, 'You've saved the Living Woods!\nThank you!'),
    0x1365DEC: (0xCCCC0101, '  Obtained Fang of Wind.'),
    0x1365DED: (0xCCCC0101, 'I will now sleep until the wounds that Hein\ninflicted upon me heal themselves...'),
    0x1365DEE: (0xCCCC0101, 'For a thousand years I shall sleep, and none\nshall be able to enter these woods until I awaken.'),
    0x1365DEF: (0xCCCC0101, 'Young ones, it is no coincidence that this floating\ncontinent was born a thousand years ago, when\nthe darkness engulfed the world...'),
    0x1365DF0: (0xCCCC0101, 'and that you have been chosen to become the\nWarriors of the Light a thousand years later.'),
    0x1365DF1: (0xCCCC0101, 'Young ones, you must leave this floating continent...'),
    0x1365DF2: (0xCCCC0101, 'and go to the world of darkness--the surface\nworld.'),
    0x1365DF3: (0xCCCC0101, '  %shuyaku1%\nThe surface world...?'),
    0x1365DF4: (0xCCCC0101, 'You must make haste! If you do not go now, it\nwill be a thousand years until you may go again!'),
    0x1365DF5: (0xCCCC0101, 'Goodbye...goodbye, and good luck!'),
    0x1CD1F45: (0xCCCC0101, '  Desch\nFaeries...I've never seen anything like them\nbefore.'),
    0x1CD1F46: (0xCCCC0101, '  %shuyaku2%\nI got it!'),
    0x1CD1F47: (0xCCCC0101, 'The soldiers of Argus are being controlled by\nthe wizard Hein!'),
    0x1CD1F48: (0xCCCC0101, '  %shuyaku4%\nWhat could this malfeasant Hein be after,\nI wonder...?'),
}