items = {
    0xF43B4: (0xCCCC0101, 'The fire crystal is in danger!\nWarriors of the Light, you have to hurry!'),
    0xF43B5: (0xCCCC0101, 'We got one horn back, but now both are\ngone! I guess that just goes to show you\nsomething, but I'm not sure what.'),
    0xF43B6: (0xCCCC0101, 'Lali-ho!\nBoth horns are back!\nHip-hip-lali-ho!'),
    0xF43B7: (0xCCCC0101, 'The fire crystal is safe, but we have\nto learn to protect the horns better! \nSecurity first, lali-ho!'),
    0xF43B8: (0xCCCC0101, 'Both horns are back!\nRally-ho...uh, I mean, lali-ho!'),
    0x9CB65D: (0xCCCC0101, 'The two horns made of ice!\nThey're our treasure, our precious!'),
    0x9CB65E: (0xCCCC0101, 'One of them was plundered and pilfered!\nStolen by a scoundrel!\nIt must be found!'),
    0x9CB6C1: (0xCCCC0101, 'Gutsco the Rogue! He stole a horn!\nSmart he is, but a rascal too!'),
    0x9CB725: (0xCCCC0101, 'Warriors of the Light, did you ever know...\nthat out to sea, far, far to the east, is a\npeninsula with a village called Gysahl?'),
    0x9CB789: (0xCCCC0101, 'We put a ward around the shrine!\nNo one can get close! We'll defend\nthe last horn!'),
    0x9CB7ED: (0xCCCC0101, 'There was a shiny tower to the north!\nAfter the earthquake, it was gone...\nBut there's a big hole where it was!'),
    0x9CB851: (0xCCCC0101, 'Stop! The dwarven treasury's up ahead!\nAll non-dwarves are forbidden to enter!'),
    0x9CB8B5: (0xCCCC0101, 'Gutsco must've known that dwarves can't swim!\nThat sneak went into the underground lake to\nmake his getaway! '),
    0x9CB8B6: (0xCCCC0101, 'Warriors of the Light! You have to go after\nthat nefarious no-gooder and take back\nthe missing Horn of Ice!'),
    0x9D047D: (0xCCCC0101, 'Thank you, lali-ho!\nThe Horn of Ice is back! Hence, there is much\nrejoicing! Lali-hooooooo!'),
    0x9D04E1: (0xCCCC0101, 'The king said he wanted to thank the Warriors of\nthe Light for bringing back the horn!'),
    0x9D04E2: (0xCCCC0101, 'Gutsco it was! He took both Horns of Ice, and\nran away to the cave to the north!\nWe're in big, big trouble!'),
    0x9D0545: (0xCCCC0101, 'Warriors of the Light, did you ever know...\nthat out to sea, far, far to the east, is a\npeninsula with a village called Gysahl?'),
    0x9D05A9: (0xCCCC0101, 'We put a ward around the shrine!\nNo one can get close! We'll defend\nthe last horn!'),
    0x9D060D: (0xCCCC0101, 'There was a shiny tower to the north!\nAfter the earthquake, it was gone...\nBut there's a big hole where it was!'),
    0x9D0671: (0xCCCC0101, 'Stop! The dwarven treasury's up ahead!\nAll non-dwarves are forbidden to enter!'),
    0x9D06D5: (0xCCCC0101, '...Lali-ho-no! Now both have been stolen!'),
    0x9D06D6: (0xCCCC0101, 'Gutsco must have gone to the mountain to\nthe north! Please, take the horns back from\nthat scoundrel!'),
    0x9D5365: (0xCCCC0101, 'Warriors of the Light, did you ever know...\nthat out to sea, far, far to the east, is a\npeninsula with a village called Gysahl?'),
    0x9D542D: (0xCCCC0101, 'There are many beautiful women in the village\nof Gysahl! And what's more, you'll even find a\nkey maker there!'),
    0x9D5491: (0xCCCC0101, 'Our treasure's yours! Follow me, and behold\nthe dwarven moonwalk! Come, come!'),
    0x9D54F5: (0xCCCC0101, 'Thank you again!\nHere, take this! It's yours! You'll find more in\nthe village of Gysahl!'),
    0x9D54F7: (0xCCCC0101, '  Obtained Magic Key.'),
    0x9D54F8: (0xCCCC0101, 'Magic keys can open anything, but they'll\nbreak once you use them!'),
    0x9D54F8: (0xCCCC0101, 'Magic keys can open anything, but they'll\nbreak once you use them!'),
    0x1354C15: (0xCCCC0101, 'That rascal Gutsco's made off with a Horn of Ice!\nHe made his getaway through the underground\nlake!'),
    0x1354C16: (0xCCCC0101, 'We can't go after him...because dwarves can't\nswim! But you're humans! Humans can swim!\nYou must aid us with your amphibious abilities!'),
    0x1354C79: (0xCCCC0101, '  An invisible wall blocks your path.'),
    0x1359A35: (0xCCCC0101, 'Lali-ho! Lali-ho! Thank you for returning the horn!'),
    0x1359A36: (0xCCCC0101, 'Put it back on the shrine, beside the other!\nI'll take down the ward! Here we go, lali-ho!'),
    0x1359A37: (0xCCCC0101, 'You can approach the shrine now, and\nput the horn back where it belongs!'),
    0x1359A38: (0xCCCC0101, 'Lali-ho! Lali-ho! Thank you for returning the horn!'),
    0x1359A99: (0xCCCC0101, '  Gutsco the Rogue\nHaw haw haw! I was disguised as your shadow!\nThanks for leading me up onto the shrine!'),
    0x1359A9A: (0xCCCC0101, 'Now both horns are mine!'),
    0x1359A9B: (0xCCCC0101, '  Gutsco steals the Horns of Ice!'),
    0x1359A9C: (0xCCCC0101, '  %shuyaku1%\nWha...? How'd you do that!? And why do you keep\nstealing the horns in the first place?'),
    0x1359A9D: (0xCCCC0101, '  Gutsco the Rogue\nYou silly twits! These are the Horns of Ice,\nwards against the fire crystal's flame!'),
    0x1359A9E: (0xCCCC0101, 'They are the key to the tunnel leading to the\ncrystal! Now that I have them both, the power\nof the crystal of fire is mine! Mine!'),
}