items = {
    0xF4245: (0xCCCC0101, '  %lead_player_name%\nAhhh... I slept like a log!'),
    0xF4245: (0xCCCC0101, '  %lead_player_name%\nAhhh... I slept like a log!'),
    0xF4245: (0xCCCC0101, '  %lead_player_name%\nAhhh... I slept like a log!'),
    0xF4246: (0xCCCC0101, '  HP and MP restored.'),
    0xF4246: (0xCCCC0101, '  HP and MP restored.'),
    0xF4246: (0xCCCC0101, '  HP and MP restored.'),
    0xF425E: (0xCCCC0101, 'Let me give you a brief description of your jobs.'),
    0xF425F: (0xCCCC0101, 'Freelancers can use low-level magic, but their\nbase attributes are pretty low.'),
    0xF4260: (0xCCCC0101, 'The way of the onion knight is a long and hard\none...but once you master the job, the rewards\njust might be worth it!'),
    0xF4261: (0xCCCC0101, 'Warriors are weapons experts. Their Advance\nability allows them to deal even more damage\nthan normal, but they also get hit a lot harder.'),
    0xF4262: (0xCCCC0101, 'Monks are very resilient melee fighters. Their\nRetaliate ability allows them to counterattack\nwhile on the defensive.'),
    0xF4263: (0xCCCC0101, 'White mages are casters who specialize in\nrestorative magic. They're not physically\nstrong, but their willpower is incomparable!'),
    0xF4264: (0xCCCC0101, 'Black mages are casters who specialize in\noffensive magic. Despite their appearance,\nthey can take a few hits, too.'),
    0xF4265: (0xCCCC0101, 'Red mages can use both white and black\nmagic, but they cannot use high-level\nspells from either school.'),
    0xF4266: (0xCCCC0101, 'Rangers are experts in ranged combat.\nWith their bows, they can attack for full\ndamage from even the back line!'),
    0xF4267: (0xCCCC0101, 'Knights take pride in their high defense. Their\nDefend ability allows them to step in and take\ndamage for weakened allies.'),
    0xF4268: (0xCCCC0101, 'Thieves are very fast and agile, and they can\nswing their weapons lightning-fast. They also\nhave the ability to pick locked doors.'),
    0xF4269: (0xCCCC0101, 'Scholars can examine enemies and spot\ntheir weak points. They can also enhance\nthe effects of items they use.'),
    0xF426A: (0xCCCC0101, 'Geomancers harness the power of nature itself,\nmanifested in their different terrain attacks. Their\ndamage potential rises exponentially by job level.'),
    0xF426B: (0xCCCC0101, 'Dragoons are polearm experts. Their Jump ability\nallows them to deal massive damage while being\nimpervious to enemy attacks.'),
    0xF426C: (0xCCCC0101, 'Vikings have the ability to lure enemies into\nattacking them instead of other members of\nthe party, but it's gonna hurt!'),
    0xF426D: (0xCCCC0101, 'Dark knights are warriors of the dark blade.\nTheir Souleater ability allows them to convert\ntheir life into extra damage.'),
    0xF426E: (0xCCCC0101, 'Evokers are initiates of summoning magic, able\nto randomly draw either the light or dark power\nof summoned beasts.'),
    0xF426F: (0xCCCC0101, 'Bards use their songs to enhance their party's\nperformance. The effect of their songs varies\ndepending on the harp they use.'),
    0xF4270: (0xCCCC0101, 'Black belts are experts in unarmed combat.\nThey can boost their attack power to deal massive\ndamage, but be careful not to boost too much!'),
    0xF4271: (0xCCCC0101, 'Devouts are casters who have mastered white\nmagic. They can use all white magic spells, so\nmake sure to always have one in your party!'),
    0xF4272: (0xCCCC0101, 'Magi are casters who have mastered black\nmagic. If they can learn the forbidden black\nmagic spell, they may be able to destroy all...'),
    0xF4273: (0xCCCC0101, 'Summoners are able to draw the hidden powers\nof summoned beasts. Their powers will be further\nenhanced if they can find the legendary beasts...'),
    0xF4274: (0xCCCC0101, 'Sages are those who have gained knowledge\nin all schools of arcane arts. They can use all\ntypes of spells!'),
    0xF4275: (0xCCCC0101, 'Ninja excel at using dark blades. They have the\nability to throw weapons, which deal enormous\namounts of damage.'),
    0xF4296: (0xCCCC0101, 'Their Barrage ability allows them to unleash\na hail of projectiles at the enemy!'),
    0xF4297: (0xCCCC0101, 'And they can use white magic, too!'),
    0xF4298: (0xCCCC0101, 'Their Steal ability allows them to take items\nfrom enemies. Also, everyone will take less\ndamage while escaping if they use Flee.'),
    0xF4299: (0xCCCC0101, 'They can dispel magic effects from enemies\nthey've studied. Surprisingly enough, these\nbookworms can also use magic!'),
    0x9F004D: (0xCCCC0101, 'Is that your ship in the cove? I saw that\nGoldor locked it down with a giant chain,\nso it wouldn't be going anywhere soon...'),
    0x9F0115: (0xCCCC0101, 'Legend says that four warriors from the land\nof darkness came forth and subdued the\noverflowing light.'),
    0x9F0116: (0xCCCC0101, 'Goldor is afraid that you four are those\nwarriors of legend. He put a chain on your\nship to stop you from getting to his crystal.'),
    0x9F757D: (0xCCCC0101, 'Hope you come back soon!'),
    0x9F7645: (0xCCCC0101, 'Saronia, an enormous castle city, lies to the\nnorthwest of here. I don't know why, but I hear\nits denizens are warring amongst themselves.'),
    0x1379605: (0xCCCC0101, 'Warriors of the Light...'),
    0x1379606: (0xCCCC0101, 'You must seek out Doga...'),
    0x1379607: (0xCCCC0101, 'He is the only one who can help you\ndefeat Xande.'),
    0x1379608: (0xCCCC0101, 'Seek Doga...'),
    0x1379609: (0xCCCC0101, 'on the continent of Dalg...'),
    0x137960A: (0xCCCC0101, '  %shuyaku1%\n...Whoa! What? When? How?'),
    0x137960B: (0xCCCC0101, '  %shuyaku1%\n...Where am I?'),
    0x137960C: (0xCCCC0101, '  %shuyaku2%\nWe're in Amur, the City of Water. Gramps\nfound us in the temple and brought us here.'),
    0x137960D: (0xCCCC0101, '  %shuyaku4%\nWe had been asleep for three straight days...\nand the world has changed much in that span.'),
    0x137960E: (0xCCCC0101, '  %shuyaku3%\nNo one here remembers having their time\nstopped. It's as if it never happened.'),
}