items = {
    0xF4949: (0xCCCC0101, 'Hey there!\nHow are you liking it here?'),
    0x9EFFE9: (0xCCCC0101, 'I feel like I've been dreaming for a very long\ntime...'),
    0x9F004D: (0xCCCC0101, 'Is that your ship in the cove? I saw that\nGoldor locked it down with a giant chain,\nso it wouldn't be going anywhere soon...'),
    0x9F00B1: (0xCCCC0101, 'Goldor's manor is in the hills far to the south\nof here.'),
    0x9F00B2: (0xCCCC0101, 'There's a big, scary bog in front of it. What's\nso scary about it? It's bottomless--once you\nfall in, you're not coming out!'),
    0x9F0115: (0xCCCC0101, 'Legend says that four warriors from the land\nof darkness came forth and subdued the\noverflowing light.'),
    0x9F0116: (0xCCCC0101, 'Goldor is afraid that you four are those\nwarriors of legend. He put a chain on your\nship to stop you from getting to his crystal.'),
    0x9F0241: (0xCCCC0101, 'I hear that everything in Goldor's manor is\nmade of gold...but he's so afraid someone might\nsteal them that everything's under lock and key.'),
    0x9F02A5: (0xCCCC0101, 'You can't cross the bottomless bog unless you\nhave Levigrass Shoes. I think Delilah owned a\nfew of those. You can find her in the sewers.'),
    0x9F0309: (0xCCCC0101, 'I don't know how he does it, but I hear that\nmagic bounces right off of Goldor!'),
    0x9F068D: (0xCCCC0101, 'Fantabulous!'),
    0x9F7519: (0xCCCC0101, 'Fwoo! Still groggy. It's like I've been dozing for\na real long time...'),
    0x9F757D: (0xCCCC0101, 'Hope you come back soon!'),
    0x9F75E1: (0xCCCC0101, 'Oho!\nSo your ship flies, does it!?'),
    0x9F7645: (0xCCCC0101, 'Saronia, an enormous castle city, lies to the\nnorthwest of here. I don't know why, but I hear\nits denizens are warring amongst themselves.'),
    0x9F7771: (0xCCCC0101, 'You defeated Goldor? Hah! Serves that\nelectroplated, ductile doofus right!'),
    0x9F77D5: (0xCCCC0101, 'What a lovely day it is!\nDelilah should get out of that rathole of\nhers and come see the sun!'),
    0x9F7839: (0xCCCC0101, 'So Goldor is no more...\nThough I'm glad he's gone, I can't help but pity\nthat crazy fool.'),
}