items = {
    0xF444A: (0xCCCC0101, 'Duster'),
    0x9F9BC5: (0xCCCC0101, 'Geomancy is a very difficult art to master,\nbut once you do, its effects can be\ndevastating!'),
    0x9F9C29: (0xCCCC0101, 'Geomancers harness the power of\nnature itself, and use terrain to create\nmagic-like effects in various attacks.'),
    0x9F9C8D: (0xCCCC0101, 'I heard that Saronia has the fastest airship\nknown to man!'),
    0x9F9CF1: (0xCCCC0101, 'The Dalg continent is to the south of here,\nbut its entrance is protected by a great\nwind that blows away anything that comes near.'),
    0x9F9D55: (0xCCCC0101, 'I'm searching for a sword called the "Dark\nBlade." It's no ordinary sword! It's said to have\nbeen forged out of darkness itself!'),
    0x9F9DB9: (0xCCCC0101, 'Leviathan, the great shade of the lake\nBides his time for a day he would break\nThe chains o'er his darkness, and then awake.'),
    0x9F9E1D: (0xCCCC0101, 'Lord Bahamut, the greatest drake of all\nAwaits a champion before to fall\nHis power yours alone to call.'),
    0x9F9E81: (0xCCCC0101, 'Odin supreme, the knight among knights\nFearing his own power, he sealed his blight\nForever in slumber, waiting for the light.'),
    0x9F9EE5: (0xCCCC0101, 'In ancient times, man's greatest wonder\nWas to harness light; but what a blunder!\nIts newfound induction led man to destruction'),
    0x9F9EE6: (0xCCCC0101, 'And mortals wound up six feet under.\nAnd yet with the world in distress,\nFour hailed from the world of darkness.'),
    0x9F9EE7: (0xCCCC0101, 'The light they did track down\nAnd thus brought the smack down\nThus banishing man's foolishness.'),
    0x9F9F49: (0xCCCC0101, 'This is the sound\n     when you\n          get i-teeeems!'),
    0x9F9FAD: (0xCCCC0101, 'Choc, choco-choco-choco, choco-bo!\nChoc-choc choco-chocobo,\nChoc-choc choco-chocobo, hey!'),
    0x9F9FAD: (0xCCCC0101, 'Choc, choco-choco-choco, choco-bo!\nChoc-choc choco-chocobo,\nChoc-choc choco-chocobo, hey!'),
}