items = {
    0xF444B: (0xCCCC0101, 'Replito'),
    0x9FC2D5: (0xCCCC0101, 'Let's see if it works this time...\nHiyaaah!'),
    0x9FC2D5: (0xCCCC0101, 'Let's see if it works this time...\nHiyaaah!'),
    0x9FC2D6: (0xCCCC0101, 'Oh, no... Chocobo again?\nWhat am I doing wrong...?'),
    0x9FC2D6: (0xCCCC0101, 'Oh, no... Chocobo again?\nWhat am I doing wrong...?'),
    0x9FC339: (0xCCCC0101, 'Kweh?'),
    0x9FC339: (0xCCCC0101, 'Kweh?'),
    0x9FC39D: (0xCCCC0101, 'It is said that the Great Magus Noah was\nable to summon Leviathan, and even Bahamut!'),
    0x9FC401: (0xCCCC0101, 'According to legend, both Leviathan and\nBahamut were sealed away by the great\nNoah himself.'),
    0x9FC465: (0xCCCC0101, 'Entities called forth by summoners are more\npowerful than the ones called by evokers.'),
    0x9FC4C9: (0xCCCC0101, 'Summoning is the most powerful type of\nmagic, if you know when and where to use\nit!'),
    0x9FC52D: (0xCCCC0101, 'There once was a great magus called Noah.\nHe could not only use both white and black\nmagic, but he could also use summoning magic!'),
    0x9FC591: (0xCCCC0101, 'I am a Gulgan. We have the power to glimpse\ninto the future.'),
    0x9FC592: (0xCCCC0101, 'Someone is calling for the darkness to overflow\nin this world. The same thing happened before,\nonly with light, in ancient times...'),
    0x9FC593: (0xCCCC0101, 'Whoever is calling for the darkness does\nnot seem to know one thing...'),
    0x9FC594: (0xCCCC0101, 'that an artificial imbalance between the\nworlds of light and darkness will destroy\nthem both.'),
    0x9FC5F5: (0xCCCC0101, 'The Great Magus Noah once lived on the\nDalg continent...but he passed away long\nago.'),
    0x9FC659: (0xCCCC0101, 'One of Noah's apprentices is said to guard\nthe world of dream, sleeping an eternal sleep\nsomewhere in the fjords to the south.'),
    0x9FC6BD: (0xCCCC0101, 'This is just between you and me, but rumor has\nit that there is a hidden cave underneath the\nisland shaped like a triangle.'),
}