items = {
    0xF43D4: (0xCCCC0101, 'King Gorn loved Prince Alus dearly...\nWe must do all we can to help King Alus\nin his reign!'),
    0xF43E5: (0xCCCC0101, 'Hey, did you hear? People say that King Alus\nvisited the tavern a few days ago!'),
    0xF43E6: (0xCCCC0101, 'There is an island to the southeast of here,\nwhere bards and geomancers make their\nhome. It's a strange island indeed...'),
    0xF43F0: (0xCCCC0101, 'The Great Magus Noah's apprentices were\npowerful wizards in their own right.'),
    0xF43F1: (0xCCCC0101, 'One of the Great Magus's apprentices,\nDoga, is believed to live in the continent\nwest of Amur and south of Duster.'),
    0xF43F2: (0xCCCC0101, 'The Nautilus should not sway to any\nstrong winds!'),
    0xF43F3: (0xCCCC0101, 'There is a small village in the northern end\nof this continent, populated by people who\ncan use summoning magic.'),
    0xF444C: (0xCCCC0101, 'Southwestern Saronia'),
    0xA010F5: (0xCCCC0101, 'All shops have been closed by royal decree.'),
    0xA010F6: (0xCCCC0101, 'There is one weapon shop that continues\nto defy the king.'),
    0xA01159: (0xCCCC0101, 'The king divided Saronia's army into two,\nmaking them fight each other!'),
    0xA011BD: (0xCCCC0101, 'Saronia is comprised of the castle, and\nfour outlying districts. Have you visited\nthem all?'),
    0xA01221: (0xCCCC0101, 'That lad who walked into the tavern earlier...\nHe looked very much like the prince heir.'),
    0xA01285: (0xCCCC0101, 'The king doesn't listen to anyone... The last\nperson who tried to advise him was run\nthrough on the spot.'),
    0xA012E9: (0xCCCC0101, 'Oh, where in the world is Prince Alus?'),
    0xA0134D: (0xCCCC0101, 'Kind sirs...and miss, have you seen a well-clad\nboy around the age of ten in this vicinity?'),
    0xA0134F: (0xCCCC0101, 'Prince Alus! Here, please take this with\nyou!'),
    0xA01350: (0xCCCC0101, '  Obtained Dragon Mail.'),
    0xA01351: (0xCCCC0101, 'The king has changed so suddenly...\nPlease, milord, you must make him come to his\nsenses!'),
    0xA013B1: (0xCCCC0101, '  The door is tightly shut.'),
    0xA013B3: (0xCCCC0101, 'Prince Alus, you are safe! I have escaped the\ncastle so I could give this to you!'),
    0xA013B4: (0xCCCC0101, '  Obtained Wind Spear.'),
    0xA013B5: (0xCCCC0101, 'The king has changed so suddenly...\nPlease, milord, you must make him come to his\nsenses!'),
    0xA086ED: (0xCCCC0101, 'I...I've seen it. Gigameth, the king's aide... His shadow\nwas shaped like a giant bird. It looked...it looked like\nthat fiend, Garuda...!'),
    0x138A775: (0xCCCC0101, '  %shuyaku1%\nUngh... Everyone all right?\nWhat happened?'),
    0x138A776: (0xCCCC0101, '  %shuyaku4%\nObviously, a cannon shell disabled our engine.\nBut...I do not know why they would fire at us.'),
    0x138A777: (0xCCCC0101, '  %shuyaku2%\nThe Enterprise is in pieces...\nWhat are we going to do now?'),
    0x138A778: (0xCCCC0101, '  %shuyaku4%\nThis wind... It carries the sound and scent\nof war... Best be on our guards.'),
    0x1D13E59: (0xCCCC0101, '  %shuyaku3%\nWhat's up with %shuyaku2%? Why is he so eager\nto help this prince?'),
    0x1D13E5A: (0xCCCC0101, '  %shuyaku1%\nIt's probably because someone who's even shorter\nthan him is doing his best to help his country.'),
    0x1D13E5B: (0xCCCC0101, '  %shuyaku4%\nHe does a noble thing. Do not even think of mocking\nhim, %shuyaku1%.'),
    0x1D13EBD: (0xCCCC0101, '  Prince Alus\nThis is Southwestern Saronia. Here you'll find\na tavern, and a center for chocobo research.'),
    0x1D13EBE: (0xCCCC0101, 'The tavern here used to see good business\nin the olden days...'),
    0x1D13EBF: (0xCCCC0101, '  %shuyaku3%\nHey... Aren't you a little young to be going\nin there?'),
    0x1D13EC0: (0xCCCC0101, ' Prince Alus\nDon't worry, I'm too young for such vices.'),
}