items = {
    0xF444F: (0xCCCC0101, 'Great Library of Saronia'),
    0xA060A5: (0xCCCC0101, '  Book of Owen, I\n"After many long years, it is finally complete...'),
    0xA060A6: (0xCCCC0101, 'The device will enable us to lift and control\nobjects of immense size and mass.'),
    0xA060A7: (0xCCCC0101, 'If my calculations are correct, it could even\ncontrol the very planet that we live on!"'),
    0xA06109: (0xCCCC0101, '  Book of Owen, II\n"My current project is cryostasis--freezing\nobjects for long-term conservation.'),
    0xA0610A: (0xCCCC0101, 'Poetically put, an object in cryostasis could be\nsaid to be free from the flow of time. In theory,\nthis should also be applicable to living beings."'),
    0xA0616D: (0xCCCC0101, '  Ancient Book, Part 1\n"The four giant statues will burn anyone who\ndares pass between them.'),
    0xA0616E: (0xCCCC0101, 'The four fangs that we possess are the only\nthings that grant us safe passage."'),
    0xA061D1: (0xCCCC0101, '  Ancient Book, Part 2\n"Light and darkness are kept in balance by the\ncrystals of wind, fire, water, and earth."'),
    0xA06235: (0xCCCC0101, '  Ancient Book, Part 3\n"Have we abused the power of light...?'),
    0xA06236: (0xCCCC0101, 'The light is everywhere, overflowing... There is no\nway for us to stop it. And the inevitable outcome?\nDoom..."'),
    0xA06299: (0xCCCC0101, '  Ancient Book, Part 4\n"The four warriors who came from the world\nof darkness have stopped the rampaging light.'),
    0xA0629A: (0xCCCC0101, 'Who are they? How did they come to possess\ntheir power? The only thing we know is that their\nbravery saved the world from destruction."'),
    0xA062FD: (0xCCCC0101, '  Way of the Dark Blade\n"The mountains west of Saronia hold the secret\nto the Way of the Dark Blade..."'),
    0xA06361: (0xCCCC0101, '  Perpetual Engine Theory\n"The governing principle behind the Wheel of Time\nis based on the temporal balance of antimatter..."'),
    0xA063C5: (0xCCCC0101, '  Airships in Action!\n"Our editors pick the top three most\nsensational, spectacular airships of the year!'),
    0xA063C6: (0xCCCC0101, '1st: The Diving Nautilus\n2nd: The Colossal Invincible\n3rd: The Indomitable Enterprise"'),
    0xA06429: (0xCCCC0101, '  Book of Owen, III\n"Everything is ready. I will now leave Saronia\nand depart for the experiment site.'),
    0xA0642A: (0xCCCC0101, 'I will take my son Desch, already an accomplished\nscientist himself, with me."'),
}