items = {
    0xF43BD: (0xCCCC0101, 'I've heard that a tunnel under Castle Saronia\ngoes all the way out to the sea.'),
    0xF43C7: (0xCCCC0101, 'Ancient legends speak of a dragoon defeating\nthe great avian lord single-handedly...'),
    0xF43D7: (0xCCCC0101, 'Come to think of it, Saronia changed when\nGigameth appeared. I wonder if his goal\nwas to take over the rule of Saronia...'),
    0xF444E: (0xCCCC0101, 'Northwestern Saronia'),
    0xF457E: (0xCCCC0101, 'I am a smith traveling the world in search\nof a legendary metal.'),
    0xF457E: (0xCCCC0101, 'I am a smith traveling the world in search\nof a legendary metal.'),
    0xF4592: (0xCCCC0101, '  %shuyaku4%\nYou are the master smith, are you not?\nI have a favor to ask you.'),
    0xF4593: (0xCCCC0101, 'This pendant... Can you fix it?'),
    0xF4594: (0xCCCC0101, 'It belongs to someone very dear to me.\nI will do anything you ask, if you can\nrestore it to its previous state.'),
    0xF4595: (0xCCCC0101, 'Hmm... I wouldn't do this normally, but I like\nthe look in your eyes. Let me see this\npendant of yours.'),
    0xF4596: (0xCCCC0101, 'There. It's all fixed.'),
    0xF4597: (0xCCCC0101, '  Obtained Sara's Pendant.'),
    0xF4598: (0xCCCC0101, '  %shuyaku4%\nThank you! I do not have much, but what amount\nof gil would be sufficient for your work?'),
    0xF4599: (0xCCCC0101, 'Money does not interest me... There is one item,\nhowever, that I would like to ask you to find for\nme...'),
    0xF459A: (0xCCCC0101, '  %shuyaku4%\nWhat may that be?'),
    0xF459B: (0xCCCC0101, 'Have you ever heard of "orichalcum"? It is\na metal of legend, fabled to have mystical\nproperties.'),
    0xF459C: (0xCCCC0101, 'If you find any in your travels, bring it back to\nme. Don't worry, I only want to try my hand\nat tempering it.'),
    0xF459D: (0xCCCC0101, 'Whatever I manage to craft the metal into is\nyours. What do you say?'),
    0xF459E: (0xCCCC0101, '  %shuyaku4%\nIt sounds more than fair. Any orichalcum we find\nwill be yours to challenge.'),
    0xF45A1: (0xCCCC0101, 'Remember, the metal is called orichalcum.\nBring it to me, and whatever I craft with it\nis yours.'),
    0xA013B1: (0xCCCC0101, '  The door is tightly shut.'),
    0xA05F15: (0xCCCC0101, 'This building here is the Great Library of\nSaronia! ...But it's closed now.'),
    0xA05F16: (0xCCCC0101, 'Go to the library! You will find the knowledge that\nyou seek there!'),
    0xA05FDD: (0xCCCC0101, 'You'll find a copy of every book ever written in\nthe Great Library of Saronia!'),
    0xA05FDE: (0xCCCC0101, 'Peace has returned to Saronia! Thank you!'),
    0xA06041: (0xCCCC0101, 'Shoo! Go away! The library is closed!'),
    0xA06042: (0xCCCC0101, 'King Alus instructed me to let you pass.\nGo right on ahead.'),
    0x1D18C15: (0xCCCC0101, '  Prince Alus\nThis is Northwestern Saronia. The Great Library\nis situated in this district.'),
    0x1D18C16: (0xCCCC0101, 'It is the largest library in the world, holding every\nbook ever written in known history.'),
    0x1D18C17: (0xCCCC0101, '  %shuyaku2%\nBooks...! Knowledge!'),
}