items = {
    0xF43BE: (0xCCCC0101, 'Legend says that there was a great knight in\nSaronia who was so powerful, he was feared\nby everyone in the world!'),
    0xF43C8: (0xCCCC0101, 'Saronia once had the greatest military in\nthe world, with airships and dragoons giving\nthem complete air superiority...'),
    0xF43E7: (0xCCCC0101, 'Welcome to King Alus's Saronia!'),
    0xF43E8: (0xCCCC0101, 'We will never forget you, and what you have\ndone for us. We will never forget that as long\nas there is hope, nothing is impossible!'),
    0xF43F6: (0xCCCC0101, 'Saronia will prevail! Long live King Alus!'),
    0xF4450: (0xCCCC0101, 'Northeastern Saronia'),
    0xA01159: (0xCCCC0101, 'The king divided Saronia's army into two,\nmaking them fight each other!'),
    0xA01285: (0xCCCC0101, 'The king doesn't listen to anyone... The last\nperson who tried to advise him was run\nthrough on the spot.'),
    0xA013B1: (0xCCCC0101, '  The door is tightly shut.'),
    0xA013B1: (0xCCCC0101, '  The door is tightly shut.'),
    0xA013B1: (0xCCCC0101, '  The door is tightly shut.'),
    0xA013B1: (0xCCCC0101, '  The door is tightly shut.'),
    0xA08626: (0xCCCC0101, 'May the light guide you.'),
    0xA08689: (0xCCCC0101, 'The island toward the southeast is called\nDuster, home of bards and geomancers.'),
    0xA086ED: (0xCCCC0101, 'I...I've seen it. Gigameth, the king's aide... His shadow\nwas shaped like a giant bird. It looked...it looked like\nthat fiend, Garuda...!'),
    0xA08751: (0xCCCC0101, 'No one enters Castle Saronia without the king's\npermission.'),
    0xA08752: (0xCCCC0101, 'Long live King Alus! May Saronia prevail for\neternity!'),
    0x1D1B325: (0xCCCC0101, '  Prince Alus\nThis is Northeastern Saronia. It serves as the\ncity's economic center.'),
    0x1D1B326: (0xCCCC0101, 'However, my father, the king, ordered for all the\nstores here to be closed indefinitely.'),
    0x1D1B327: (0xCCCC0101, '  %shuyaku1%\nSwell... And here I was, hoping we'd get a\nchance to buy some new weapons.'),
}