items = {
    0xF4455: (0xCCCC0101, 'Falgabard'),
    0xF45CE: (0xCCCC0101, '  %shuyaku4%\nIs this what you were looking for?'),
    0xF45CF: (0xCCCC0101, 'Yes, yes! That's unmistakably orichalcum!\nI didn't think I'd ever lay eyes on it!'),
    0xF45D0: (0xCCCC0101, 'Thanks for bringing it to me. Mind if\nI start working on it?'),
    0xF45D1: (0xCCCC0101, '  %shuyaku4%\nDo as you wish.'),
    0xF45D2: (0xCCCC0101, '  You hand over the orichalcum.'),
    0xF45D3: (0xCCCC0101, 'This is going to be quite the challenge\nindeed!'),
    0xF45D8: (0xCCCC0101, 'Ah! I was expecting you. I've succeeded\nin tempering orichalcum!'),
    0xF45D8: (0xCCCC0101, 'Ah! I was expecting you. I've succeeded\nin tempering orichalcum!'),
    0xF45D9: (0xCCCC0101, 'The result...is my best work yet, if I may say\nso myself.'),
    0xF45D9: (0xCCCC0101, 'The result...is my best work yet, if I may say\nso myself.'),
    0xF45DA: (0xCCCC0101, 'Here, it's yours, as promised. Use it well.'),
    0xF45DA: (0xCCCC0101, 'Here, it's yours, as promised. Use it well.'),
    0xF45DB: (0xCCCC0101, '  Obtained Ultima Weapon.'),
    0xF45DB: (0xCCCC0101, '  Obtained Ultima Weapon.'),
    0xF45DC: (0xCCCC0101, 'I will now continue my travels, seeking new\nmetals to temper and all that... Maybe we'll\nmeet again somewhere.'),
    0xF45DC: (0xCCCC0101, 'I will now continue my travels, seeking new\nmetals to temper and all that... Maybe we'll\nmeet again somewhere.'),
    0xF45DD: (0xCCCC0101, '  %shuyaku1%\nYeah. Good luck, then!'),
    0xF45DD: (0xCCCC0101, '  %shuyaku1%\nYeah. Good luck, then!'),
    0xF45DE: (0xCCCC0101, 'You too. Farewell!'),
    0xF45DE: (0xCCCC0101, 'You too. Farewell!'),
    0xA2A905: (0xCCCC0101, 'Welcome to Falgabard, the place of solace for\nthose who seek to train in the way of the dark\nblade...'),
    0xA2A969: (0xCCCC0101, 'Dark blades can only be wielded by those\nwho have managed to overcome the darkness\nwithin. Dark knights excel at using them.'),
    0xA2A9CD: (0xCCCC0101, 'The legendary blade Masamune has been lost\nfor ages...but I hear it lies in its hidden resting\nplace, waiting for a true master to claim it.'),
    0xA2AA31: (0xCCCC0101, 'In ancient times, there were soldiers who fought\nwith dark blades and by throwing weapons with\ntremendous power. They were called...ninja!'),
    0xA2AA95: (0xCCCC0101, 'The beasts that roam in this cave can only be\ndefeated by an adept of the dark blade! You\ndon't stand a chance!'),
    0xA2ABC1: (0xCCCC0101, 'The monsters that roam inside the Cave of Shadows\nnorth of Amur can only be defeated by dark blade \ntechniques. Many venture in, but none return.'),
    0xA2AC25: (0xCCCC0101, 'I heard that some monsters will divide and multiply\nif you attack them normally. Talk about doubling\nyour trouble!'),
}