items = {
    0x1315673: (0xCCCC0101, '...'),
    0x1315674: (0xCCCC0101, '......'),
    0x1315675: (0xCCCC0101, '  %shuyaku1%\nI'm back on the surface...'),
    0x1315676: (0xCCCC0101, 'What was that...?\nLight? Darkness? Our last hope?\nWhat was that all about?'),
    0x132DB15: (0xCCCC0101, '  Cid\nOw, my back... Well, that was entertaining,\nwasn't it? Good to see everyone's intact.'),
    0x132DB16: (0xCCCC0101, '  %shuyaku1%\n...It's weird. I feel as if we've done this\nbefore.'),
    0x132DB17: (0xCCCC0101, '  %shuyaku2%\nDid you hit your head or something? We'd\nnever even seen an airship until we met Cid.'),
    0x132DB18: (0xCCCC0101, '  %shuyaku1%\nPhew...'),
    0x134FDF5: (0xCCCC0101, '"Aieee!"\n"Yow!"\n"Ouch!"'),
    0x134FDF6: (0xCCCC0101, '  %shuyaku1%\n...The Enterprise?\nDid Desch send us here...?'),
    0x134FDF7: (0xCCCC0101, '  %shuyaku2%\nLook! The maelstrom's weakening!\nWe can get out!'),
    0x134FDF8: (0xCCCC0101, '  %shuyaku4%\nWe are in Desch's debt...'),
    0x134FDF9: (0xCCCC0101, 'We must go onwards, to the dwarves' island!'),
    0x134FDFA: (0xCCCC0101, '  %shuyaku3%\nDesch...\nPlease be safe...'),
    0x136ABAE: (0xCCCC0101, 'Ten years ago, I was flying my airship, filled\nwith passengers... It seemed to be a day like\nany other, until...'),
    0x136ABAF: (0xCCCC0101, 'Suddenly, the airship was engulfed in an\nimpenetrable darkness...'),
    0x136ABB0: (0xCCCC0101, 'Next thing I knew, my airship was in pieces.\nWe had crashed, and things were aflame\neverywhere I looked...'),
    0x136ABB1: (0xCCCC0101, 'The only survivors, aside from myself, were you\nfour... You probably don't remember--you were\nonly little kiddies then.'),
    0x137E425: (0xCCCC0101, '  The party has met an untimely end...'),
    0x137E425: (0xCCCC0101, '  The party has met an untimely end...'),
    0x13CA0A5: (0xCCCC0101, '  %shuyaku3%\nWe're almost at Canaan.'),
    0x13CA0A6: (0xCCCC0101, '  Cid\nOho! Are we, now?\nMrs. Cid must be worried about me!'),
    0x13CA0A7: (0xCCCC0101, '  Desch\nI'm getting off here, too!'),
    0x13CA0A8: (0xCCCC0101, '  %shuyaku1%\nWhy are you going to Canaan, Desch?'),
    0x13CA0A9: (0xCCCC0101, '  Desch\nWell, I have some...unfinished business, if you\nknow what I mean.'),
    0x13CA0AA: (0xCCCC0101, '  %shuyaku1%\n???'),
    0x13CA0AB: (0xCCCC0101, '  Desch\n...I have to see Salina.'),
    0x13CA0AC: (0xCCCC0101, '  %shuyaku3%\nOooh! So you've finally come to your senses!'),
    0x13CA0AD: (0xCCCC0101, '  Desch\nOh, stop it! You're embarrassing me!'),
    0x13CA0AE: (0xCCCC0101, '*Whistle*'),
    0x13CA0C2: (0xCCCC0101, '  %shuyaku4%\nMilady, let us return to Castle Sasune.'),
    0x13CA0C3: (0xCCCC0101, '  Princess Sara\nNo! I do not want to go back so soon!'),
    0x13CA0C4: (0xCCCC0101, '  %shuyaku4%\nMilady! Why...?'),
    0x13CA0C5: (0xCCCC0101, '  Princess Sara\nMen are so obtuse... Must I say it plainly?\nI want to stay with you a bit longer! There!'),
    0x13CA0C6: (0xCCCC0101, '  %shuyaku4%\n...'),
    0x13CA0C7: (0xCCCC0101, '  Princess Sara\nDon't look so surprised! Come, let us visit\nKazus and Ur first.'),
    0x13CA0C8: (0xCCCC0101, '  %shuyaku4%\nAs you wish, Milady. I will stay by your side\nuntil the end of time!'),
    0x1CAAE45: (0xCCCC0101, '  Princess Sara\nHello, there. I'm Princess Sara. What's your name?'),
    0x1CAAE46: (0xCCCC0101, '  %shuyaku1%\nI'm %shuyaku1%! Nice to meetcha!'),
    0x1CAAE47: (0xCCCC0101, '  Princess Sara\nVery nice to meet you, %shuyaku1%.'),
    0x1CAAEA9: (0xCCCC0101, '  Princess Sara\nI managed to come here on my own,\nbut I can't say I wasn't afraid...'),
    0x1CAAEAA: (0xCCCC0101, 'Thank you, %shuyaku4%.'),
    0x1CAAEAB: (0xCCCC0101, '  %shuyaku4%\nMilady, I... I could do nothing alone.\nI am sorry.'),
    0x1CAAF0D: (0xCCCC0101, '  Princess Sara\nWe must use this ring to banish\nthe Djinn and save everyone!'),
    0x1CAAF0E: (0xCCCC0101, '  %shuyaku3%\n...My father made that ring for me...'),
    0x1CAAF0F: (0xCCCC0101, '  Princess Sara\nThis ring is yours!?'),
    0x1CAAF10: (0xCCCC0101, '  %shuyaku3%\nI-I... I'm kidding! Never mind.'),
    0x1CAAF71: (0xCCCC0101, '  Princess Sara\nThe Djinn is a fire elemental.\nIt should be susceptible to cold.'),
    0x1CAAF72: (0xCCCC0101, '  %shuyaku2%\nSo...it should be weak to the Blizzard spell,\nand the Antarctic Wind item.'),
    0x1CAAFD5: (0xCCCC0101, '  Princess Sara\nOh! I should tell you about saving and\nquicksaving!'),
    0x1CAAFD5: (0xCCCC0101, '  Princess Sara\nOh! I should tell you about saving and\nquicksaving!'),
    0x1CAAFD6: (0xCCCC0101, 'Select "Save" from the menu to save\nyour progress, but remember, you can only\nsave when you are out on the world map.'),
    0x1CAAFD6: (0xCCCC0101, 'Select "Save" from the menu to save\nyour progress, but remember, you can only\nsave when you are out on the world map.'),
    0x1CAAFD7: (0xCCCC0101, 'There are two kinds of quicksave: auto, and manual.'),
    0x1CAAFD7: (0xCCCC0101, 'There are two kinds of quicksave: auto, and manual.'),
    0x1CAAFD8: (0xCCCC0101, 'Quicksave data disappears once you resume\nplay, so don't forget to save or quicksave\nagain when you need to take a break.'),
    0x1CAAFD8: (0xCCCC0101, 'Quicksave data disappears once you resume\nplay, so don't forget to save or quicksave\nagain when you need to take a break.'),
    0x1CAAFD9: (0xCCCC0101, 'Auto quicksave takes place automatically as you\nproceed along.'),
    0x1CAAFDA: (0xCCCC0101, 'Manual quicksave, though, lets you save your game\nwherever you like.'),
    0x1CAAFDB: (0xCCCC0101, 'Quicksaving manually lets you save inside towns and\ncaves as well.'),
    0x1CAFC65: (0xCCCC0101, '  Princess Sara\nThe blessed spring flows below Castle\nSasune. Let us hurry inside!'),
    0x1CB2375: (0xCCCC0101, '  Cid\nI'm Cid, creator of the airship! I'm all\nfamous, y'know? No autographs, please.'),
    0x1CB2376: (0xCCCC0101, 'Mrs. Cid's been waiting a mighty\nlong time for me to come back.'),
    0x1CB2377: (0xCCCC0101, 'But Nelv Valley's been blocked off\nby a huge rock, and no one can get\nthrough to Canaan...'),
    0x1CB23D9: (0xCCCC0101, '  Cid\nYou know what? If we put a mythril ram on the\nairship, we might just plow through that rock!'),
    0x1CB23DA: (0xCCCC0101, 'Takka in Kazus could build us one, I reckon...'),
    0x1CB243D: (0xCCCC0101, '  Cid\n...Hey, wasn't %shuyaku3%\nwith you?'),
    0x1CB243E: (0xCCCC0101, '  %shuyaku1%\nShe was...but her dad took her\nback home.'),
    0x1CB243F: (0xCCCC0101, '  Cid\nHuh. At least it's good to know\nshe's safe and sound.'),
    0x1CB2440: (0xCCCC0101, '  %shuyaku2%\nBut that's no good! She's supposed to\ncome with us on our journey!'),
    0x1CB24A1: (0xCCCC0101, '  Cid\nThanks to Takka's mythril ram, the\nairship's a whole lot hardier!'),
    0x1CB24A2: (0xCCCC0101, 'Now let's go show that rock in Nelv\nwho's boss, eh?'),
    0x1CB9A99: (0xCCCC0101, '  Desch\nSorry I dragged you all into this... But thanks to\nyou, I've been able to satisfy my curiosity!'),
    0x1CB9A9A: (0xCCCC0101, '  %shuyaku3%\nJust finish whatever you need to do and go see\nSalina! She's been waiting for you all this time!'),
    0x1CBE6C5: (0xCCCC0101, '  Desch\nI'm glad I met you guys. It was getting kinda lonely\nout here.'),
    0x1CBE6C6: (0xCCCC0101, '  %shuyaku3%\nSo...what's it like to not remember anything?'),
    0x1CBE6C7: (0xCCCC0101, '  Desch\nNot so bad. Except for that nagging feeling there's\nsomething I gotta do...but I can't remember what.'),
    0x1CBE729: (0xCCCC0101, '  Desch\nThat gnomish village that I heard about in Canaan\nshould be somewhere around here...'),
    0x1CBE72A: (0xCCCC0101, 'You'll all have to shrink down to gnomish size\nwith the Mini spell if you wanna go in, though!'),
    0x1CBE72B: (0xCCCC0101, '  %shuyaku2%\nAww... I was hoping I wouldn't be the shortest kid\nfor once...'),
    0x1CBE78D: (0xCCCC0101, '  Desch\nOnce shrunk, your weapons won't do much good\nagainst enemies... Only magic is unaffected by size.'),
    0x1CBE78E: (0xCCCC0101, 'You should change to a job that can use spells.\nAt least, you'll get to put the power you got from\nthe crystal to good use.'),
    0x1CBE78F: (0xCCCC0101, 'And being in the rear line would also be good.\nReally, trust me on this!'),
    0x1CBE7F1: (0xCCCC0101, '  Desch\nLook how tiny we are...\nTalk about shrinkage!'),
    0x1CBE7F2: (0xCCCC0101, 'Weapons won't do us much good now.\nMagic is the way to go!'),
    0x1CBE7F3: (0xCCCC0101, '  %shuyaku4%\nChanging jobs may be the key when facing\na seemingly unconquerable challenge.'),
    0x1CC5BF5: (0xCCCC0101, '  Desch\nSo you guys are the Warriors of the Light, huh?\nI don't know what it means, but it sounds cool!'),
    0x1CC5BF6: (0xCCCC0101, 'Any chance I can be a Warrior of the Light\nlike you?'),
    0x1CC5BF7: (0xCCCC0101, '  %shuyaku3%\nDidn't you say you had something important\nto do...?'),
    0x1CC5BF8: (0xCCCC0101, '  Desch\nHmm... I felt something...like my blood was boiling,\nbut it's gone now.'),
    0x1CC5BF9: (0xCCCC0101, 'Must've been my imagination.'),
    0x1CC8305: (0xCCCC0101, '  Desch\nWe did it! We've got our own ship! Now we can go\nto exotic ports, and meet even more exotic women!'),
    0x1CC8306: (0xCCCC0101, '  %shuyaku3%\nWhat!? I can't believe you! I knew I was right\nwhen I told Salina to forget about you! Oooh!'),
    0x1CC8307: (0xCCCC0101, '  Desch\nHey! I was just kidding!\nYeesh, talk about touchy...'),
    0x1CC8369: (0xCCCC0101, '  Desch\nKing Argus! We should go see him! I heard in Canaan\nthat he knows the secret of airship engines.'),
    0x1CC836A: (0xCCCC0101, '  %shuyaku2%\nJust what is it that keeps them up in the air?\nI'd like to ride in an airship again, that's for sure.'),
    0x1CC836B: (0xCCCC0101, '  %shuyaku1%\nI don't know about that... I don't have very fond\nmemories of my last airship ride...'),
    0x1CC83CD: (0xCCCC0101, '  Desch\nI heard a rumor that the sightless Gulgans\nmake their home in a hidden valley.'),
    0x1CC83CE: (0xCCCC0101, 'Even though they're blind, rumor has it that\nthey can see into the future!'),
    0x1CC83CF: (0xCCCC0101, '  %shuyaku4%\nTruly? These Gulgans are diviners? I am not\nsure if such powers are a boon or a curse...'),
    0x1CCAA15: (0xCCCC0101, '  Desch\nThose soldiers've made a real mess of this town,\nthat's for sure.'),
    0x1CCAA16: (0xCCCC0101, '  %shuyaku4%\nBut can they truly be King Argus's men? I cannot\nbelieve the king would order such heinous acts...'),
    0x1CCAA17: (0xCCCC0101, '  %shuyaku2%\nThe soldiers' attacks began after the earthquake...\nMaybe the two are connected, somehow.'),
    0x1CCD125: (0xCCCC0101, '  Desch\nThis village seems awfully familiar... All this talk\nabout light and darkness...'),
    0x1CCD126: (0xCCCC0101, '  Desch\nWha...? Hey!'),
    0x1CCD127: (0xCCCC0101, 'I remember! I remember now...'),
    0x1CCD128: (0xCCCC0101, 'The powers of darkness...they stopped the flow\nof time on the surface world.'),
    0x1CCD129: (0xCCCC0101, 'That's how this floating continent was born...'),
    0x1CCD12A: (0xCCCC0101, '  %shuyaku4%\nWhat gibberish is that? The floating continent\ntheorem was already hard to take in...'),
    0x1CCD12B: (0xCCCC0101, '  %shuyaku2%\nDo you mean there are other continents...aside from\nour own?'),
    0x1CCD12C: (0xCCCC0101, '  Desch\nI... I don't know. I feel so strange...'),
    0x1CCF835: (0xCCCC0101, '  Desch\nI gotta go to the Tower of Owen... I can feel it.'),
    0x1CCF836: (0xCCCC0101, 'I believe what the old man said. I have to go\nthere and fulfill my destiny!'),
    0x1CCF839: (0xCCCC0101, '  %shuyaku3%\nAre you absolutely completely certainly sure?\nI really have a bad feeling about this...'),
    0x1CD4655: (0xCCCC0101, '  Desch\n...There's no one here.'),
    0x1CD4656: (0xCCCC0101, '  %shuyaku4%\nA very unwise strategic decision.'),
    0x1CD4657: (0xCCCC0101, '  %shuyaku3%\nMaybe they're out pillaging villages like\ngood soldiers of doom?'),
    0x1CD6D65: (0xCCCC0101, '  Desch\nWhat was that voice...?\nWait...I think I remember being here before.'),
    0x1CD6D66: (0xCCCC0101, '  %shuyaku3%\nYou have to try to remember, Desch!'),
    0x1CD6D67: (0xCCCC0101, '  Desch\n...Never mind. Let's go.'),
    0x1CD6DC9: (0xCCCC0101, '  Desch\n...The Ancients...? Yes, that's it! I'm one of the\nAncients!'),
    0x1CD6DCA: (0xCCCC0101, '  %shuyaku3%\nAre you saying you're one of the descendants\nof the Ancients?'),
    0x1CD6DCB: (0xCCCC0101, '  Desch\nNo... I... I can almost remember everything now...\nSo close...'),
    0x1CD6E2D: (0xCCCC0101, '  %shuyaku1%\nThat voice again! Show yourself! We'll show YOU\nwho's lost!'),
    0x1CD6E2E: (0xCCCC0101, '  Desch\nWait. There should be a switch that opens a\nhidden passageway somewhere around here.'),
    0x1CD70E9: (0xCCCC0101, '  Desch\nI...I think I've been here before.'),
    0x1CF6935: (0xCCCC0101, '  %shuyaku1%\nAaah! Wh-what is this cloud!?\nIt's...it's draining my strength away...'),
    0x1CF6937: (0xCCCC0101, '  %shuyaku4%\nHold on! Our answers lie on the surface!\nWe must reach it!'),
    0x1CF9045: (0xCCCC0101, '  %shuyaku1%\nIs this the surface...?\nIt's so...sprawling!'),
    0x1CFB755: (0xCCCC0101, '  Aria\nThe light of the crystal within you has freed me\nfrom this frozen time.'),
    0x1CFB756: (0xCCCC0101, 'If the water crystal regains its former power,\nwe may be able to banish the darkness from this\nland and restore the flow of time.'),
    0x1CFB757: (0xCCCC0101, '  %shuyaku1%\nYou're the first person to see the power\nof the crystals... So it's really inside us?'),
    0x1CFB7BB: (0xCCCC0101, '  Aria\nI can see why the crystals chose you...'),
    0x1CFB7BC: (0xCCCC0101, 'I can feel the light within you...strong, yet gentle...'),
    0x1D13DF5: (0xCCCC0101, '  Prince Alus\nMy father has changed... It is as if some evil\nspirit has taken ahold of him.'),
    0x1D13DF6: (0xCCCC0101, '  %shuyaku2%\nThere must be a reason for all this... I'm sure\nhe'll explain it to you when we meet him.'),
    0x1D13DF7: (0xCCCC0101, '  Prince Alus\nI would like to talk to him... But he told me to\nnever return to the castle.'),
    0x1D13E59: (0xCCCC0101, '  %shuyaku3%\nWhat's up with %shuyaku2%? Why is he so eager\nto help this prince?'),
    0x1D13E5A: (0xCCCC0101, '  %shuyaku1%\nIt's probably because someone who's even shorter\nthan him is doing his best to help his country.'),
    0x1D13E5B: (0xCCCC0101, '  %shuyaku4%\nHe does a noble thing. Do not even think of mocking\nhim, %shuyaku1%.'),
    0x1D13EBD: (0xCCCC0101, '  Prince Alus\nThis is Southwestern Saronia. Here you'll find\na tavern, and a center for chocobo research.'),
    0x1D13EBE: (0xCCCC0101, 'The tavern here used to see good business\nin the olden days...'),
    0x1D13EBF: (0xCCCC0101, '  %shuyaku3%\nHey... Aren't you a little young to be going\nin there?'),
    0x1D13EC0: (0xCCCC0101, ' Prince Alus\nDon't worry, I'm too young for such vices.'),
    0x1D16505: (0xCCCC0101, '  Prince Alus\nThis is Southeastern Saronia. The tower at\nthe center is called the Dragon Spire.'),
    0x1D16506: (0xCCCC0101, 'It was built by dragoons, also known as\ndragon knights.'),
    0x1D16507: (0xCCCC0101, '  %shuyaku4%\nDragoons, you say...'),
    0x1D18C15: (0xCCCC0101, '  Prince Alus\nThis is Northwestern Saronia. The Great Library\nis situated in this district.'),
    0x1D18C16: (0xCCCC0101, 'It is the largest library in the world, holding every\nbook ever written in known history.'),
    0x1D18C17: (0xCCCC0101, '  %shuyaku2%\nBooks...! Knowledge!'),
    0x1D1B325: (0xCCCC0101, '  Prince Alus\nThis is Northeastern Saronia. It serves as the\ncity's economic center.'),
    0x1D1B326: (0xCCCC0101, 'However, my father, the king, ordered for all the\nstores here to be closed indefinitely.'),
    0x1D1B327: (0xCCCC0101, '  %shuyaku1%\nSwell... And here I was, hoping we'd get a\nchance to buy some new weapons.'),
    0x1D22855: (0xCCCC0101, '  Doga\nThe Circle leads to a rift between dimensions...\nAnd that is where the key to Eureka lies.'),
    0x1D22856: (0xCCCC0101, '  %shuyaku2%\nEureka...?'),
    0x1D22857: (0xCCCC0101, '  Doga\nEureka is the land where weapons of incredible\npower, created by the Ancients, are sealed.'),
    0x1D22858: (0xCCCC0101, 'Only these forbidden weapons, combined with\nthe power of the Warriors of the Light, will be\npowerful enough to defeat Xande.'),
    0x1D228B9: (0xCCCC0101, '  Doga\nXande is the one who engulfed this world in\ndarkness and stopped the flow of time.'),
    0x1D228BA: (0xCCCC0101, 'The unnatural nature of that action ripped\na section of this planet away from the\nrest...'),
    0x1D228BB: (0xCCCC0101, 'That section is what you have come to call\nthe floating continent!'),
    0x1D2291D: (0xCCCC0101, '  %shuyaku1%\nThere's something we have to tell you...\nGoldor destroyed the earth crystal.'),
    0x1D2291E: (0xCCCC0101, '  Doga\nGoldor?'),
    0x1D2291F: (0xCCCC0101, 'No matter; that crystal was a fake. I created it\nmyself. It was only good for making gold.'),
    0x1D22920: (0xCCCC0101, 'Do not worry. The earth crystal is still whole and\nsafe...but its location is unknown.'),
    0x1D24F65: (0xCCCC0101, '  %shuyaku1%\nI can understand why Xande would be angry\nfor being made mortal...'),
    0x1D24F66: (0xCCCC0101, '  Doga\nBut mortality is what makes life so precious\nin the first place.'),
    0x1D24F67: (0xCCCC0101, 'It is not how long you live, but what you make\nof the time you have in this world.'),
    0x1D24FC9: (0xCCCC0101, '  Doga\nI had heard from Unei that the Warriors of the\nLight had been chosen...'),
    0x1D24FCA: (0xCCCC0101, 'Still, I did not expect you to be so...young.'),
    0x1D24FCB: (0xCCCC0101, '  Doga\nNo... Perhaps you were chosen exactly because\nyou are so young, and full of hope...'),
    0x1D312B5: (0xCCCC0101, '  Unei\nIt's been a while. How've you been?\nI'm impressed you made it here so fast.'),
    0x1D312B6: (0xCCCC0101, '  Unei\nHave you forgotten already? We've met in\nyour dreams once before!'),
    0x1D312B7: (0xCCCC0101, '  %shuyaku1%\nIn our dreams...?'),
    0x1D312B8: (0xCCCC0101, 'Oh! That voice we heard in Amur, it was\nyou?'),
    0x1D312B9: (0xCCCC0101, '  Unei\nHo ho ho! I told you I was the guardian of\nthe world of dream, didn't I?'),
    0x1D31319: (0xCCCC0101, '  Unei\nEven when Xande stopped the flow of time in the\nreal world, the world of dream was unaffected.'),
    0x1D3131A: (0xCCCC0101, 'For the thousand years that the real world\nstood still, I was watching it from the dreamworld...'),
    0x1D3131B: (0xCCCC0101, 'And I saw that something evil was using\nits power to create a giant earthquake on the\nfloating continent!'),
    0x1D3131C: (0xCCCC0101, '  Unei\nXande himself couldn't have done it, since the flow\nof time is stopped for him as well. Who could it be?'),
    0x1D3137D: (0xCCCC0101, '  Unei\nI still can't believe that Xande would do this...'),
    0x1D3137E: (0xCCCC0101, 'You have to get the Invincible, and stop him\nas soon as you can!'),
    0x1D3137F: (0xCCCC0101, 'The Invincible is the largest airship that the\nAncients ever built! Its engine is powerful\nenough to fly above the highest mountains!'),
    0x1D31380: (0xCCCC0101, 'Once the Invincible's up and running, you have\nto find the Fang of Earth--it's the last fang\nyou'll need to get past Xande's four statues!'),
    0x1D31381: (0xCCCC0101, 'Now, let's hurry! The Invincible should be in\nthe Ancient Ruins up north from the shrine\nI was sleeping in!'),
    0x1D339C5: (0xCCCC0101, '  Unei\nThe gift that Noah gave Xande--mortality--is\nthe greatest gift of all...'),
    0x1D339C6: (0xCCCC0101, 'I guess Xande couldn't see that.'),
    0x1D339C7: (0xCCCC0101, '  %shuyaku1%\nBeing able to die is a great gift...?\nI still don't get it...'),
    0x1D339C8: (0xCCCC0101, '  Unei\nHeh heh heh. You're still too young to understand,\nmy boy.'),
    0x1D33A29: (0xCCCC0101, '  Unei\nThe Fang of Earth should be in the Cave of\nShadows in the mountains north of Amur.'),
    0x1D33A2A: (0xCCCC0101, 'Once you have the four fangs, you can destroy\nthe four ancient statues that guard the Syrcus\nTower, and stop Xande before it's too late.'),
    0x1D33A2B: (0xCCCC0101, '  %shuyaku2%\nI never realized these fangs had such power...'),
}